GET http://localhost:3000/api/users
Content-Type: application/json

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Test",
  "email": "test@mail.com",
  "password": "rahasia",
  "role": "USER",
  "bankAccount": "12345678"
}