###
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "udibagas@gmail.com",
  "password": "bismillah12345"
}

###
POST http://localhost:3000/api/notifications/testNotif
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjY1LCJuYW1lIjoiQmFnYXMgVWRpIFNhaHNhbmdrYSIsImVtYWlsIjoidWRpYmFnYXNAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNzIyMzMwNjQ3LCJleHAiOjE3MjI5MzU0NDd9.mM0FxGoZh44ccJM1iZvWVmHYhx4KO0YYFDHbQtlhY9I