
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApprovalSetting` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApprovalSetting
 * 
 */
export type ApprovalSettingModel = runtime.Types.Result.DefaultSelection<Prisma.$ApprovalSettingPayload>

export type AggregateApprovalSetting = {
  _count: ApprovalSettingCountAggregateOutputType | null
  _avg: ApprovalSettingAvgAggregateOutputType | null
  _sum: ApprovalSettingSumAggregateOutputType | null
  _min: ApprovalSettingMinAggregateOutputType | null
  _max: ApprovalSettingMaxAggregateOutputType | null
}

export type ApprovalSettingAvgAggregateOutputType = {
  id: number | null
  companyId: number | null
}

export type ApprovalSettingSumAggregateOutputType = {
  id: number | null
  companyId: number | null
}

export type ApprovalSettingMinAggregateOutputType = {
  id: number | null
  companyId: number | null
  approvalType: $Enums.ApprovalType | null
  paymentType: $Enums.PaymentType | null
  nkpType: $Enums.NkpType | null
}

export type ApprovalSettingMaxAggregateOutputType = {
  id: number | null
  companyId: number | null
  approvalType: $Enums.ApprovalType | null
  paymentType: $Enums.PaymentType | null
  nkpType: $Enums.NkpType | null
}

export type ApprovalSettingCountAggregateOutputType = {
  id: number
  companyId: number
  approvalType: number
  paymentType: number
  nkpType: number
  _all: number
}


export type ApprovalSettingAvgAggregateInputType = {
  id?: true
  companyId?: true
}

export type ApprovalSettingSumAggregateInputType = {
  id?: true
  companyId?: true
}

export type ApprovalSettingMinAggregateInputType = {
  id?: true
  companyId?: true
  approvalType?: true
  paymentType?: true
  nkpType?: true
}

export type ApprovalSettingMaxAggregateInputType = {
  id?: true
  companyId?: true
  approvalType?: true
  paymentType?: true
  nkpType?: true
}

export type ApprovalSettingCountAggregateInputType = {
  id?: true
  companyId?: true
  approvalType?: true
  paymentType?: true
  nkpType?: true
  _all?: true
}

export type ApprovalSettingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApprovalSetting to aggregate.
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalSettings to fetch.
   */
  orderBy?: Prisma.ApprovalSettingOrderByWithRelationInput | Prisma.ApprovalSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApprovalSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApprovalSettings
  **/
  _count?: true | ApprovalSettingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApprovalSettingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApprovalSettingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApprovalSettingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApprovalSettingMaxAggregateInputType
}

export type GetApprovalSettingAggregateType<T extends ApprovalSettingAggregateArgs> = {
      [P in keyof T & keyof AggregateApprovalSetting]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApprovalSetting[P]>
    : Prisma.GetScalarType<T[P], AggregateApprovalSetting[P]>
}




export type ApprovalSettingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApprovalSettingWhereInput
  orderBy?: Prisma.ApprovalSettingOrderByWithAggregationInput | Prisma.ApprovalSettingOrderByWithAggregationInput[]
  by: Prisma.ApprovalSettingScalarFieldEnum[] | Prisma.ApprovalSettingScalarFieldEnum
  having?: Prisma.ApprovalSettingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApprovalSettingCountAggregateInputType | true
  _avg?: ApprovalSettingAvgAggregateInputType
  _sum?: ApprovalSettingSumAggregateInputType
  _min?: ApprovalSettingMinAggregateInputType
  _max?: ApprovalSettingMaxAggregateInputType
}

export type ApprovalSettingGroupByOutputType = {
  id: number
  companyId: number
  approvalType: $Enums.ApprovalType
  paymentType: $Enums.PaymentType | null
  nkpType: $Enums.NkpType | null
  _count: ApprovalSettingCountAggregateOutputType | null
  _avg: ApprovalSettingAvgAggregateOutputType | null
  _sum: ApprovalSettingSumAggregateOutputType | null
  _min: ApprovalSettingMinAggregateOutputType | null
  _max: ApprovalSettingMaxAggregateOutputType | null
}

export type GetApprovalSettingGroupByPayload<T extends ApprovalSettingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApprovalSettingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApprovalSettingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApprovalSettingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApprovalSettingGroupByOutputType[P]>
      }
    >
  >



export type ApprovalSettingWhereInput = {
  AND?: Prisma.ApprovalSettingWhereInput | Prisma.ApprovalSettingWhereInput[]
  OR?: Prisma.ApprovalSettingWhereInput[]
  NOT?: Prisma.ApprovalSettingWhereInput | Prisma.ApprovalSettingWhereInput[]
  id?: Prisma.IntFilter<"ApprovalSetting"> | number
  companyId?: Prisma.IntFilter<"ApprovalSetting"> | number
  approvalType?: Prisma.EnumApprovalTypeFilter<"ApprovalSetting"> | $Enums.ApprovalType
  paymentType?: Prisma.EnumPaymentTypeNullableFilter<"ApprovalSetting"> | $Enums.PaymentType | null
  nkpType?: Prisma.EnumNkpTypeNullableFilter<"ApprovalSetting"> | $Enums.NkpType | null
  Company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
  ApprovalSettingItem?: Prisma.ApprovalSettingItemListRelationFilter
}

export type ApprovalSettingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  approvalType?: Prisma.SortOrder
  paymentType?: Prisma.SortOrderInput | Prisma.SortOrder
  nkpType?: Prisma.SortOrderInput | Prisma.SortOrder
  Company?: Prisma.CompanyOrderByWithRelationInput
  ApprovalSettingItem?: Prisma.ApprovalSettingItemOrderByRelationAggregateInput
}

export type ApprovalSettingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  companyId_approvalType_paymentType_nkpType?: Prisma.ApprovalSettingCompanyIdApprovalTypePaymentTypeNkpTypeCompoundUniqueInput
  AND?: Prisma.ApprovalSettingWhereInput | Prisma.ApprovalSettingWhereInput[]
  OR?: Prisma.ApprovalSettingWhereInput[]
  NOT?: Prisma.ApprovalSettingWhereInput | Prisma.ApprovalSettingWhereInput[]
  companyId?: Prisma.IntFilter<"ApprovalSetting"> | number
  approvalType?: Prisma.EnumApprovalTypeFilter<"ApprovalSetting"> | $Enums.ApprovalType
  paymentType?: Prisma.EnumPaymentTypeNullableFilter<"ApprovalSetting"> | $Enums.PaymentType | null
  nkpType?: Prisma.EnumNkpTypeNullableFilter<"ApprovalSetting"> | $Enums.NkpType | null
  Company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
  ApprovalSettingItem?: Prisma.ApprovalSettingItemListRelationFilter
}, "id" | "companyId_approvalType_paymentType_nkpType">

export type ApprovalSettingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  approvalType?: Prisma.SortOrder
  paymentType?: Prisma.SortOrderInput | Prisma.SortOrder
  nkpType?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ApprovalSettingCountOrderByAggregateInput
  _avg?: Prisma.ApprovalSettingAvgOrderByAggregateInput
  _max?: Prisma.ApprovalSettingMaxOrderByAggregateInput
  _min?: Prisma.ApprovalSettingMinOrderByAggregateInput
  _sum?: Prisma.ApprovalSettingSumOrderByAggregateInput
}

export type ApprovalSettingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApprovalSettingScalarWhereWithAggregatesInput | Prisma.ApprovalSettingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApprovalSettingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApprovalSettingScalarWhereWithAggregatesInput | Prisma.ApprovalSettingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ApprovalSetting"> | number
  companyId?: Prisma.IntWithAggregatesFilter<"ApprovalSetting"> | number
  approvalType?: Prisma.EnumApprovalTypeWithAggregatesFilter<"ApprovalSetting"> | $Enums.ApprovalType
  paymentType?: Prisma.EnumPaymentTypeNullableWithAggregatesFilter<"ApprovalSetting"> | $Enums.PaymentType | null
  nkpType?: Prisma.EnumNkpTypeNullableWithAggregatesFilter<"ApprovalSetting"> | $Enums.NkpType | null
}

export type ApprovalSettingCreateInput = {
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
  Company: Prisma.CompanyCreateNestedOneWithoutApprovalSettingInput
  ApprovalSettingItem?: Prisma.ApprovalSettingItemCreateNestedManyWithoutApprovalSettingInput
}

export type ApprovalSettingUncheckedCreateInput = {
  id?: number
  companyId: number
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
  ApprovalSettingItem?: Prisma.ApprovalSettingItemUncheckedCreateNestedManyWithoutApprovalSettingInput
}

export type ApprovalSettingUpdateInput = {
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
  Company?: Prisma.CompanyUpdateOneRequiredWithoutApprovalSettingNestedInput
  ApprovalSettingItem?: Prisma.ApprovalSettingItemUpdateManyWithoutApprovalSettingNestedInput
}

export type ApprovalSettingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  companyId?: Prisma.IntFieldUpdateOperationsInput | number
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
  ApprovalSettingItem?: Prisma.ApprovalSettingItemUncheckedUpdateManyWithoutApprovalSettingNestedInput
}

export type ApprovalSettingCreateManyInput = {
  id?: number
  companyId: number
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
}

export type ApprovalSettingUpdateManyMutationInput = {
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
}

export type ApprovalSettingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  companyId?: Prisma.IntFieldUpdateOperationsInput | number
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
}

export type ApprovalSettingListRelationFilter = {
  every?: Prisma.ApprovalSettingWhereInput
  some?: Prisma.ApprovalSettingWhereInput
  none?: Prisma.ApprovalSettingWhereInput
}

export type ApprovalSettingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ApprovalSettingCompanyIdApprovalTypePaymentTypeNkpTypeCompoundUniqueInput = {
  companyId: number
  approvalType: $Enums.ApprovalType
  paymentType: $Enums.PaymentType
  nkpType: $Enums.NkpType
}

export type ApprovalSettingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  approvalType?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  nkpType?: Prisma.SortOrder
}

export type ApprovalSettingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type ApprovalSettingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  approvalType?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  nkpType?: Prisma.SortOrder
}

export type ApprovalSettingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  approvalType?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  nkpType?: Prisma.SortOrder
}

export type ApprovalSettingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
}

export type ApprovalSettingScalarRelationFilter = {
  is?: Prisma.ApprovalSettingWhereInput
  isNot?: Prisma.ApprovalSettingWhereInput
}

export type ApprovalSettingCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput> | Prisma.ApprovalSettingCreateWithoutCompanyInput[] | Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput | Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ApprovalSettingCreateManyCompanyInputEnvelope
  connect?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
}

export type ApprovalSettingUncheckedCreateNestedManyWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput> | Prisma.ApprovalSettingCreateWithoutCompanyInput[] | Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput | Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput[]
  createMany?: Prisma.ApprovalSettingCreateManyCompanyInputEnvelope
  connect?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
}

export type ApprovalSettingUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput> | Prisma.ApprovalSettingCreateWithoutCompanyInput[] | Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput | Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ApprovalSettingUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ApprovalSettingUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ApprovalSettingCreateManyCompanyInputEnvelope
  set?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  disconnect?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  delete?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  connect?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  update?: Prisma.ApprovalSettingUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ApprovalSettingUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ApprovalSettingUpdateManyWithWhereWithoutCompanyInput | Prisma.ApprovalSettingUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ApprovalSettingScalarWhereInput | Prisma.ApprovalSettingScalarWhereInput[]
}

export type ApprovalSettingUncheckedUpdateManyWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput> | Prisma.ApprovalSettingCreateWithoutCompanyInput[] | Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput[]
  connectOrCreate?: Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput | Prisma.ApprovalSettingCreateOrConnectWithoutCompanyInput[]
  upsert?: Prisma.ApprovalSettingUpsertWithWhereUniqueWithoutCompanyInput | Prisma.ApprovalSettingUpsertWithWhereUniqueWithoutCompanyInput[]
  createMany?: Prisma.ApprovalSettingCreateManyCompanyInputEnvelope
  set?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  disconnect?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  delete?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  connect?: Prisma.ApprovalSettingWhereUniqueInput | Prisma.ApprovalSettingWhereUniqueInput[]
  update?: Prisma.ApprovalSettingUpdateWithWhereUniqueWithoutCompanyInput | Prisma.ApprovalSettingUpdateWithWhereUniqueWithoutCompanyInput[]
  updateMany?: Prisma.ApprovalSettingUpdateManyWithWhereWithoutCompanyInput | Prisma.ApprovalSettingUpdateManyWithWhereWithoutCompanyInput[]
  deleteMany?: Prisma.ApprovalSettingScalarWhereInput | Prisma.ApprovalSettingScalarWhereInput[]
}

export type EnumApprovalTypeFieldUpdateOperationsInput = {
  set?: $Enums.ApprovalType
}

export type NullableEnumPaymentTypeFieldUpdateOperationsInput = {
  set?: $Enums.PaymentType | null
}

export type NullableEnumNkpTypeFieldUpdateOperationsInput = {
  set?: $Enums.NkpType | null
}

export type ApprovalSettingCreateNestedOneWithoutApprovalSettingItemInput = {
  create?: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUncheckedCreateWithoutApprovalSettingItemInput>
  connectOrCreate?: Prisma.ApprovalSettingCreateOrConnectWithoutApprovalSettingItemInput
  connect?: Prisma.ApprovalSettingWhereUniqueInput
}

export type ApprovalSettingUpdateOneRequiredWithoutApprovalSettingItemNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUncheckedCreateWithoutApprovalSettingItemInput>
  connectOrCreate?: Prisma.ApprovalSettingCreateOrConnectWithoutApprovalSettingItemInput
  upsert?: Prisma.ApprovalSettingUpsertWithoutApprovalSettingItemInput
  connect?: Prisma.ApprovalSettingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ApprovalSettingUpdateToOneWithWhereWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUpdateWithoutApprovalSettingItemInput>, Prisma.ApprovalSettingUncheckedUpdateWithoutApprovalSettingItemInput>
}

export type ApprovalSettingCreateWithoutCompanyInput = {
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
  ApprovalSettingItem?: Prisma.ApprovalSettingItemCreateNestedManyWithoutApprovalSettingInput
}

export type ApprovalSettingUncheckedCreateWithoutCompanyInput = {
  id?: number
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
  ApprovalSettingItem?: Prisma.ApprovalSettingItemUncheckedCreateNestedManyWithoutApprovalSettingInput
}

export type ApprovalSettingCreateOrConnectWithoutCompanyInput = {
  where: Prisma.ApprovalSettingWhereUniqueInput
  create: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput>
}

export type ApprovalSettingCreateManyCompanyInputEnvelope = {
  data: Prisma.ApprovalSettingCreateManyCompanyInput | Prisma.ApprovalSettingCreateManyCompanyInput[]
  skipDuplicates?: boolean
}

export type ApprovalSettingUpsertWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ApprovalSettingWhereUniqueInput
  update: Prisma.XOR<Prisma.ApprovalSettingUpdateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedCreateWithoutCompanyInput>
}

export type ApprovalSettingUpdateWithWhereUniqueWithoutCompanyInput = {
  where: Prisma.ApprovalSettingWhereUniqueInput
  data: Prisma.XOR<Prisma.ApprovalSettingUpdateWithoutCompanyInput, Prisma.ApprovalSettingUncheckedUpdateWithoutCompanyInput>
}

export type ApprovalSettingUpdateManyWithWhereWithoutCompanyInput = {
  where: Prisma.ApprovalSettingScalarWhereInput
  data: Prisma.XOR<Prisma.ApprovalSettingUpdateManyMutationInput, Prisma.ApprovalSettingUncheckedUpdateManyWithoutCompanyInput>
}

export type ApprovalSettingScalarWhereInput = {
  AND?: Prisma.ApprovalSettingScalarWhereInput | Prisma.ApprovalSettingScalarWhereInput[]
  OR?: Prisma.ApprovalSettingScalarWhereInput[]
  NOT?: Prisma.ApprovalSettingScalarWhereInput | Prisma.ApprovalSettingScalarWhereInput[]
  id?: Prisma.IntFilter<"ApprovalSetting"> | number
  companyId?: Prisma.IntFilter<"ApprovalSetting"> | number
  approvalType?: Prisma.EnumApprovalTypeFilter<"ApprovalSetting"> | $Enums.ApprovalType
  paymentType?: Prisma.EnumPaymentTypeNullableFilter<"ApprovalSetting"> | $Enums.PaymentType | null
  nkpType?: Prisma.EnumNkpTypeNullableFilter<"ApprovalSetting"> | $Enums.NkpType | null
}

export type ApprovalSettingCreateWithoutApprovalSettingItemInput = {
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
  Company: Prisma.CompanyCreateNestedOneWithoutApprovalSettingInput
}

export type ApprovalSettingUncheckedCreateWithoutApprovalSettingItemInput = {
  id?: number
  companyId: number
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
}

export type ApprovalSettingCreateOrConnectWithoutApprovalSettingItemInput = {
  where: Prisma.ApprovalSettingWhereUniqueInput
  create: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUncheckedCreateWithoutApprovalSettingItemInput>
}

export type ApprovalSettingUpsertWithoutApprovalSettingItemInput = {
  update: Prisma.XOR<Prisma.ApprovalSettingUpdateWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUncheckedUpdateWithoutApprovalSettingItemInput>
  create: Prisma.XOR<Prisma.ApprovalSettingCreateWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUncheckedCreateWithoutApprovalSettingItemInput>
  where?: Prisma.ApprovalSettingWhereInput
}

export type ApprovalSettingUpdateToOneWithWhereWithoutApprovalSettingItemInput = {
  where?: Prisma.ApprovalSettingWhereInput
  data: Prisma.XOR<Prisma.ApprovalSettingUpdateWithoutApprovalSettingItemInput, Prisma.ApprovalSettingUncheckedUpdateWithoutApprovalSettingItemInput>
}

export type ApprovalSettingUpdateWithoutApprovalSettingItemInput = {
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
  Company?: Prisma.CompanyUpdateOneRequiredWithoutApprovalSettingNestedInput
}

export type ApprovalSettingUncheckedUpdateWithoutApprovalSettingItemInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  companyId?: Prisma.IntFieldUpdateOperationsInput | number
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
}

export type ApprovalSettingCreateManyCompanyInput = {
  id?: number
  approvalType: $Enums.ApprovalType
  paymentType?: $Enums.PaymentType | null
  nkpType?: $Enums.NkpType | null
}

export type ApprovalSettingUpdateWithoutCompanyInput = {
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
  ApprovalSettingItem?: Prisma.ApprovalSettingItemUpdateManyWithoutApprovalSettingNestedInput
}

export type ApprovalSettingUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
  ApprovalSettingItem?: Prisma.ApprovalSettingItemUncheckedUpdateManyWithoutApprovalSettingNestedInput
}

export type ApprovalSettingUncheckedUpdateManyWithoutCompanyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  approvalType?: Prisma.EnumApprovalTypeFieldUpdateOperationsInput | $Enums.ApprovalType
  paymentType?: Prisma.NullableEnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType | null
  nkpType?: Prisma.NullableEnumNkpTypeFieldUpdateOperationsInput | $Enums.NkpType | null
}


/**
 * Count Type ApprovalSettingCountOutputType
 */

export type ApprovalSettingCountOutputType = {
  ApprovalSettingItem: number
}

export type ApprovalSettingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ApprovalSettingItem?: boolean | ApprovalSettingCountOutputTypeCountApprovalSettingItemArgs
}

/**
 * ApprovalSettingCountOutputType without action
 */
export type ApprovalSettingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSettingCountOutputType
   */
  select?: Prisma.ApprovalSettingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ApprovalSettingCountOutputType without action
 */
export type ApprovalSettingCountOutputTypeCountApprovalSettingItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApprovalSettingItemWhereInput
}


export type ApprovalSettingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  approvalType?: boolean
  paymentType?: boolean
  nkpType?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  ApprovalSettingItem?: boolean | Prisma.ApprovalSetting$ApprovalSettingItemArgs<ExtArgs>
  _count?: boolean | Prisma.ApprovalSettingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalSetting"]>

export type ApprovalSettingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  approvalType?: boolean
  paymentType?: boolean
  nkpType?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalSetting"]>

export type ApprovalSettingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  approvalType?: boolean
  paymentType?: boolean
  nkpType?: boolean
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalSetting"]>

export type ApprovalSettingSelectScalar = {
  id?: boolean
  companyId?: boolean
  approvalType?: boolean
  paymentType?: boolean
  nkpType?: boolean
}

export type ApprovalSettingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "companyId" | "approvalType" | "paymentType" | "nkpType", ExtArgs["result"]["approvalSetting"]>
export type ApprovalSettingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
  ApprovalSettingItem?: boolean | Prisma.ApprovalSetting$ApprovalSettingItemArgs<ExtArgs>
  _count?: boolean | Prisma.ApprovalSettingCountOutputTypeDefaultArgs<ExtArgs>
}
export type ApprovalSettingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}
export type ApprovalSettingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}

export type $ApprovalSettingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApprovalSetting"
  objects: {
    Company: Prisma.$CompanyPayload<ExtArgs>
    ApprovalSettingItem: Prisma.$ApprovalSettingItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    companyId: number
    approvalType: $Enums.ApprovalType
    paymentType: $Enums.PaymentType | null
    nkpType: $Enums.NkpType | null
  }, ExtArgs["result"]["approvalSetting"]>
  composites: {}
}

export type ApprovalSettingGetPayload<S extends boolean | null | undefined | ApprovalSettingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload, S>

export type ApprovalSettingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApprovalSettingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApprovalSettingCountAggregateInputType | true
  }

export interface ApprovalSettingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApprovalSetting'], meta: { name: 'ApprovalSetting' } }
  /**
   * Find zero or one ApprovalSetting that matches the filter.
   * @param {ApprovalSettingFindUniqueArgs} args - Arguments to find a ApprovalSetting
   * @example
   * // Get one ApprovalSetting
   * const approvalSetting = await prisma.approvalSetting.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApprovalSettingFindUniqueArgs>(args: Prisma.SelectSubset<T, ApprovalSettingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApprovalSetting that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApprovalSettingFindUniqueOrThrowArgs} args - Arguments to find a ApprovalSetting
   * @example
   * // Get one ApprovalSetting
   * const approvalSetting = await prisma.approvalSetting.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApprovalSettingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApprovalSettingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApprovalSetting that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingFindFirstArgs} args - Arguments to find a ApprovalSetting
   * @example
   * // Get one ApprovalSetting
   * const approvalSetting = await prisma.approvalSetting.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApprovalSettingFindFirstArgs>(args?: Prisma.SelectSubset<T, ApprovalSettingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApprovalSetting that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingFindFirstOrThrowArgs} args - Arguments to find a ApprovalSetting
   * @example
   * // Get one ApprovalSetting
   * const approvalSetting = await prisma.approvalSetting.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApprovalSettingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApprovalSettingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApprovalSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApprovalSettings
   * const approvalSettings = await prisma.approvalSetting.findMany()
   * 
   * // Get first 10 ApprovalSettings
   * const approvalSettings = await prisma.approvalSetting.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const approvalSettingWithIdOnly = await prisma.approvalSetting.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApprovalSettingFindManyArgs>(args?: Prisma.SelectSubset<T, ApprovalSettingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApprovalSetting.
   * @param {ApprovalSettingCreateArgs} args - Arguments to create a ApprovalSetting.
   * @example
   * // Create one ApprovalSetting
   * const ApprovalSetting = await prisma.approvalSetting.create({
   *   data: {
   *     // ... data to create a ApprovalSetting
   *   }
   * })
   * 
   */
  create<T extends ApprovalSettingCreateArgs>(args: Prisma.SelectSubset<T, ApprovalSettingCreateArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApprovalSettings.
   * @param {ApprovalSettingCreateManyArgs} args - Arguments to create many ApprovalSettings.
   * @example
   * // Create many ApprovalSettings
   * const approvalSetting = await prisma.approvalSetting.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApprovalSettingCreateManyArgs>(args?: Prisma.SelectSubset<T, ApprovalSettingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApprovalSettings and returns the data saved in the database.
   * @param {ApprovalSettingCreateManyAndReturnArgs} args - Arguments to create many ApprovalSettings.
   * @example
   * // Create many ApprovalSettings
   * const approvalSetting = await prisma.approvalSetting.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApprovalSettings and only return the `id`
   * const approvalSettingWithIdOnly = await prisma.approvalSetting.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApprovalSettingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApprovalSettingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApprovalSetting.
   * @param {ApprovalSettingDeleteArgs} args - Arguments to delete one ApprovalSetting.
   * @example
   * // Delete one ApprovalSetting
   * const ApprovalSetting = await prisma.approvalSetting.delete({
   *   where: {
   *     // ... filter to delete one ApprovalSetting
   *   }
   * })
   * 
   */
  delete<T extends ApprovalSettingDeleteArgs>(args: Prisma.SelectSubset<T, ApprovalSettingDeleteArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApprovalSetting.
   * @param {ApprovalSettingUpdateArgs} args - Arguments to update one ApprovalSetting.
   * @example
   * // Update one ApprovalSetting
   * const approvalSetting = await prisma.approvalSetting.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApprovalSettingUpdateArgs>(args: Prisma.SelectSubset<T, ApprovalSettingUpdateArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApprovalSettings.
   * @param {ApprovalSettingDeleteManyArgs} args - Arguments to filter ApprovalSettings to delete.
   * @example
   * // Delete a few ApprovalSettings
   * const { count } = await prisma.approvalSetting.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApprovalSettingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApprovalSettingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApprovalSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApprovalSettings
   * const approvalSetting = await prisma.approvalSetting.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApprovalSettingUpdateManyArgs>(args: Prisma.SelectSubset<T, ApprovalSettingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApprovalSettings and returns the data updated in the database.
   * @param {ApprovalSettingUpdateManyAndReturnArgs} args - Arguments to update many ApprovalSettings.
   * @example
   * // Update many ApprovalSettings
   * const approvalSetting = await prisma.approvalSetting.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApprovalSettings and only return the `id`
   * const approvalSettingWithIdOnly = await prisma.approvalSetting.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApprovalSettingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApprovalSettingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApprovalSetting.
   * @param {ApprovalSettingUpsertArgs} args - Arguments to update or create a ApprovalSetting.
   * @example
   * // Update or create a ApprovalSetting
   * const approvalSetting = await prisma.approvalSetting.upsert({
   *   create: {
   *     // ... data to create a ApprovalSetting
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApprovalSetting we want to update
   *   }
   * })
   */
  upsert<T extends ApprovalSettingUpsertArgs>(args: Prisma.SelectSubset<T, ApprovalSettingUpsertArgs<ExtArgs>>): Prisma.Prisma__ApprovalSettingClient<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApprovalSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingCountArgs} args - Arguments to filter ApprovalSettings to count.
   * @example
   * // Count the number of ApprovalSettings
   * const count = await prisma.approvalSetting.count({
   *   where: {
   *     // ... the filter for the ApprovalSettings we want to count
   *   }
   * })
  **/
  count<T extends ApprovalSettingCountArgs>(
    args?: Prisma.Subset<T, ApprovalSettingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApprovalSettingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApprovalSetting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApprovalSettingAggregateArgs>(args: Prisma.Subset<T, ApprovalSettingAggregateArgs>): Prisma.PrismaPromise<GetApprovalSettingAggregateType<T>>

  /**
   * Group by ApprovalSetting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalSettingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApprovalSettingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApprovalSettingGroupByArgs['orderBy'] }
      : { orderBy?: ApprovalSettingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApprovalSettingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApprovalSettingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApprovalSetting model
 */
readonly fields: ApprovalSettingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApprovalSetting.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApprovalSettingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Company<T extends Prisma.CompanyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CompanyDefaultArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  ApprovalSettingItem<T extends Prisma.ApprovalSetting$ApprovalSettingItemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApprovalSetting$ApprovalSettingItemArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApprovalSetting model
 */
export interface ApprovalSettingFieldRefs {
  readonly id: Prisma.FieldRef<"ApprovalSetting", 'Int'>
  readonly companyId: Prisma.FieldRef<"ApprovalSetting", 'Int'>
  readonly approvalType: Prisma.FieldRef<"ApprovalSetting", 'ApprovalType'>
  readonly paymentType: Prisma.FieldRef<"ApprovalSetting", 'PaymentType'>
  readonly nkpType: Prisma.FieldRef<"ApprovalSetting", 'NkpType'>
}
    

// Custom InputTypes
/**
 * ApprovalSetting findUnique
 */
export type ApprovalSettingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalSetting to fetch.
   */
  where: Prisma.ApprovalSettingWhereUniqueInput
}

/**
 * ApprovalSetting findUniqueOrThrow
 */
export type ApprovalSettingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalSetting to fetch.
   */
  where: Prisma.ApprovalSettingWhereUniqueInput
}

/**
 * ApprovalSetting findFirst
 */
export type ApprovalSettingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalSetting to fetch.
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalSettings to fetch.
   */
  orderBy?: Prisma.ApprovalSettingOrderByWithRelationInput | Prisma.ApprovalSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApprovalSettings.
   */
  cursor?: Prisma.ApprovalSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalSettings.
   */
  distinct?: Prisma.ApprovalSettingScalarFieldEnum | Prisma.ApprovalSettingScalarFieldEnum[]
}

/**
 * ApprovalSetting findFirstOrThrow
 */
export type ApprovalSettingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalSetting to fetch.
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalSettings to fetch.
   */
  orderBy?: Prisma.ApprovalSettingOrderByWithRelationInput | Prisma.ApprovalSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApprovalSettings.
   */
  cursor?: Prisma.ApprovalSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalSettings.
   */
  distinct?: Prisma.ApprovalSettingScalarFieldEnum | Prisma.ApprovalSettingScalarFieldEnum[]
}

/**
 * ApprovalSetting findMany
 */
export type ApprovalSettingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalSettings to fetch.
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalSettings to fetch.
   */
  orderBy?: Prisma.ApprovalSettingOrderByWithRelationInput | Prisma.ApprovalSettingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApprovalSettings.
   */
  cursor?: Prisma.ApprovalSettingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalSettings.
   */
  distinct?: Prisma.ApprovalSettingScalarFieldEnum | Prisma.ApprovalSettingScalarFieldEnum[]
}

/**
 * ApprovalSetting create
 */
export type ApprovalSettingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * The data needed to create a ApprovalSetting.
   */
  data: Prisma.XOR<Prisma.ApprovalSettingCreateInput, Prisma.ApprovalSettingUncheckedCreateInput>
}

/**
 * ApprovalSetting createMany
 */
export type ApprovalSettingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApprovalSettings.
   */
  data: Prisma.ApprovalSettingCreateManyInput | Prisma.ApprovalSettingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApprovalSetting createManyAndReturn
 */
export type ApprovalSettingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * The data used to create many ApprovalSettings.
   */
  data: Prisma.ApprovalSettingCreateManyInput | Prisma.ApprovalSettingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ApprovalSetting update
 */
export type ApprovalSettingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * The data needed to update a ApprovalSetting.
   */
  data: Prisma.XOR<Prisma.ApprovalSettingUpdateInput, Prisma.ApprovalSettingUncheckedUpdateInput>
  /**
   * Choose, which ApprovalSetting to update.
   */
  where: Prisma.ApprovalSettingWhereUniqueInput
}

/**
 * ApprovalSetting updateMany
 */
export type ApprovalSettingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApprovalSettings.
   */
  data: Prisma.XOR<Prisma.ApprovalSettingUpdateManyMutationInput, Prisma.ApprovalSettingUncheckedUpdateManyInput>
  /**
   * Filter which ApprovalSettings to update
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * Limit how many ApprovalSettings to update.
   */
  limit?: number
}

/**
 * ApprovalSetting updateManyAndReturn
 */
export type ApprovalSettingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * The data used to update ApprovalSettings.
   */
  data: Prisma.XOR<Prisma.ApprovalSettingUpdateManyMutationInput, Prisma.ApprovalSettingUncheckedUpdateManyInput>
  /**
   * Filter which ApprovalSettings to update
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * Limit how many ApprovalSettings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ApprovalSetting upsert
 */
export type ApprovalSettingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * The filter to search for the ApprovalSetting to update in case it exists.
   */
  where: Prisma.ApprovalSettingWhereUniqueInput
  /**
   * In case the ApprovalSetting found by the `where` argument doesn't exist, create a new ApprovalSetting with this data.
   */
  create: Prisma.XOR<Prisma.ApprovalSettingCreateInput, Prisma.ApprovalSettingUncheckedCreateInput>
  /**
   * In case the ApprovalSetting was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApprovalSettingUpdateInput, Prisma.ApprovalSettingUncheckedUpdateInput>
}

/**
 * ApprovalSetting delete
 */
export type ApprovalSettingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  /**
   * Filter which ApprovalSetting to delete.
   */
  where: Prisma.ApprovalSettingWhereUniqueInput
}

/**
 * ApprovalSetting deleteMany
 */
export type ApprovalSettingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApprovalSettings to delete
   */
  where?: Prisma.ApprovalSettingWhereInput
  /**
   * Limit how many ApprovalSettings to delete.
   */
  limit?: number
}

/**
 * ApprovalSetting.ApprovalSettingItem
 */
export type ApprovalSetting$ApprovalSettingItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSettingItem
   */
  select?: Prisma.ApprovalSettingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSettingItem
   */
  omit?: Prisma.ApprovalSettingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingItemInclude<ExtArgs> | null
  where?: Prisma.ApprovalSettingItemWhereInput
  orderBy?: Prisma.ApprovalSettingItemOrderByWithRelationInput | Prisma.ApprovalSettingItemOrderByWithRelationInput[]
  cursor?: Prisma.ApprovalSettingItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ApprovalSettingItemScalarFieldEnum | Prisma.ApprovalSettingItemScalarFieldEnum[]
}

/**
 * ApprovalSetting without action
 */
export type ApprovalSettingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
}
