
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApprovalItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApprovalItem
 * 
 */
export type ApprovalItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ApprovalItemPayload>

export type AggregateApprovalItem = {
  _count: ApprovalItemCountAggregateOutputType | null
  _avg: ApprovalItemAvgAggregateOutputType | null
  _sum: ApprovalItemSumAggregateOutputType | null
  _min: ApprovalItemMinAggregateOutputType | null
  _max: ApprovalItemMaxAggregateOutputType | null
}

export type ApprovalItemAvgAggregateOutputType = {
  id: number | null
  approvalId: number | null
  order: number | null
  userId: number | null
}

export type ApprovalItemSumAggregateOutputType = {
  id: number | null
  approvalId: number | null
  order: number | null
  userId: number | null
}

export type ApprovalItemMinAggregateOutputType = {
  id: number | null
  approvalId: number | null
  order: number | null
  userId: number | null
  status: $Enums.ApprovalStatus | null
  remarks: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ApprovalItemMaxAggregateOutputType = {
  id: number | null
  approvalId: number | null
  order: number | null
  userId: number | null
  status: $Enums.ApprovalStatus | null
  remarks: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ApprovalItemCountAggregateOutputType = {
  id: number
  approvalId: number
  order: number
  userId: number
  status: number
  remarks: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ApprovalItemAvgAggregateInputType = {
  id?: true
  approvalId?: true
  order?: true
  userId?: true
}

export type ApprovalItemSumAggregateInputType = {
  id?: true
  approvalId?: true
  order?: true
  userId?: true
}

export type ApprovalItemMinAggregateInputType = {
  id?: true
  approvalId?: true
  order?: true
  userId?: true
  status?: true
  remarks?: true
  createdAt?: true
  updatedAt?: true
}

export type ApprovalItemMaxAggregateInputType = {
  id?: true
  approvalId?: true
  order?: true
  userId?: true
  status?: true
  remarks?: true
  createdAt?: true
  updatedAt?: true
}

export type ApprovalItemCountAggregateInputType = {
  id?: true
  approvalId?: true
  order?: true
  userId?: true
  status?: true
  remarks?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ApprovalItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApprovalItem to aggregate.
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalItems to fetch.
   */
  orderBy?: Prisma.ApprovalItemOrderByWithRelationInput | Prisma.ApprovalItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApprovalItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApprovalItems
  **/
  _count?: true | ApprovalItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApprovalItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApprovalItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApprovalItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApprovalItemMaxAggregateInputType
}

export type GetApprovalItemAggregateType<T extends ApprovalItemAggregateArgs> = {
      [P in keyof T & keyof AggregateApprovalItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApprovalItem[P]>
    : Prisma.GetScalarType<T[P], AggregateApprovalItem[P]>
}




export type ApprovalItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApprovalItemWhereInput
  orderBy?: Prisma.ApprovalItemOrderByWithAggregationInput | Prisma.ApprovalItemOrderByWithAggregationInput[]
  by: Prisma.ApprovalItemScalarFieldEnum[] | Prisma.ApprovalItemScalarFieldEnum
  having?: Prisma.ApprovalItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApprovalItemCountAggregateInputType | true
  _avg?: ApprovalItemAvgAggregateInputType
  _sum?: ApprovalItemSumAggregateInputType
  _min?: ApprovalItemMinAggregateInputType
  _max?: ApprovalItemMaxAggregateInputType
}

export type ApprovalItemGroupByOutputType = {
  id: number
  approvalId: number | null
  order: number
  userId: number
  status: $Enums.ApprovalStatus | null
  remarks: string | null
  createdAt: Date
  updatedAt: Date | null
  _count: ApprovalItemCountAggregateOutputType | null
  _avg: ApprovalItemAvgAggregateOutputType | null
  _sum: ApprovalItemSumAggregateOutputType | null
  _min: ApprovalItemMinAggregateOutputType | null
  _max: ApprovalItemMaxAggregateOutputType | null
}

export type GetApprovalItemGroupByPayload<T extends ApprovalItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApprovalItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApprovalItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApprovalItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApprovalItemGroupByOutputType[P]>
      }
    >
  >



export type ApprovalItemWhereInput = {
  AND?: Prisma.ApprovalItemWhereInput | Prisma.ApprovalItemWhereInput[]
  OR?: Prisma.ApprovalItemWhereInput[]
  NOT?: Prisma.ApprovalItemWhereInput | Prisma.ApprovalItemWhereInput[]
  id?: Prisma.IntFilter<"ApprovalItem"> | number
  approvalId?: Prisma.IntNullableFilter<"ApprovalItem"> | number | null
  order?: Prisma.IntFilter<"ApprovalItem"> | number
  userId?: Prisma.IntFilter<"ApprovalItem"> | number
  status?: Prisma.EnumApprovalStatusNullableFilter<"ApprovalItem"> | $Enums.ApprovalStatus | null
  remarks?: Prisma.StringNullableFilter<"ApprovalItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ApprovalItem"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"ApprovalItem"> | Date | string | null
  approval?: Prisma.XOR<Prisma.ApprovalNullableScalarRelationFilter, Prisma.ApprovalWhereInput> | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ApprovalItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  approval?: Prisma.ApprovalOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type ApprovalItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ApprovalItemWhereInput | Prisma.ApprovalItemWhereInput[]
  OR?: Prisma.ApprovalItemWhereInput[]
  NOT?: Prisma.ApprovalItemWhereInput | Prisma.ApprovalItemWhereInput[]
  approvalId?: Prisma.IntNullableFilter<"ApprovalItem"> | number | null
  order?: Prisma.IntFilter<"ApprovalItem"> | number
  userId?: Prisma.IntFilter<"ApprovalItem"> | number
  status?: Prisma.EnumApprovalStatusNullableFilter<"ApprovalItem"> | $Enums.ApprovalStatus | null
  remarks?: Prisma.StringNullableFilter<"ApprovalItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ApprovalItem"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"ApprovalItem"> | Date | string | null
  approval?: Prisma.XOR<Prisma.ApprovalNullableScalarRelationFilter, Prisma.ApprovalWhereInput> | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ApprovalItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ApprovalItemCountOrderByAggregateInput
  _avg?: Prisma.ApprovalItemAvgOrderByAggregateInput
  _max?: Prisma.ApprovalItemMaxOrderByAggregateInput
  _min?: Prisma.ApprovalItemMinOrderByAggregateInput
  _sum?: Prisma.ApprovalItemSumOrderByAggregateInput
}

export type ApprovalItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApprovalItemScalarWhereWithAggregatesInput | Prisma.ApprovalItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApprovalItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApprovalItemScalarWhereWithAggregatesInput | Prisma.ApprovalItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ApprovalItem"> | number
  approvalId?: Prisma.IntNullableWithAggregatesFilter<"ApprovalItem"> | number | null
  order?: Prisma.IntWithAggregatesFilter<"ApprovalItem"> | number
  userId?: Prisma.IntWithAggregatesFilter<"ApprovalItem"> | number
  status?: Prisma.EnumApprovalStatusNullableWithAggregatesFilter<"ApprovalItem"> | $Enums.ApprovalStatus | null
  remarks?: Prisma.StringNullableWithAggregatesFilter<"ApprovalItem"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ApprovalItem"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ApprovalItem"> | Date | string | null
}

export type ApprovalItemCreateInput = {
  order: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  approval?: Prisma.ApprovalCreateNestedOneWithoutItemsInput
  user: Prisma.UserCreateNestedOneWithoutApprovalItemsInput
}

export type ApprovalItemUncheckedCreateInput = {
  id?: number
  approvalId?: number | null
  order: number
  userId: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ApprovalItemUpdateInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approval?: Prisma.ApprovalUpdateOneWithoutItemsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutApprovalItemsNestedInput
}

export type ApprovalItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  approvalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApprovalItemCreateManyInput = {
  id?: number
  approvalId?: number | null
  order: number
  userId: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ApprovalItemUpdateManyMutationInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApprovalItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  approvalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApprovalItemListRelationFilter = {
  every?: Prisma.ApprovalItemWhereInput
  some?: Prisma.ApprovalItemWhereInput
  none?: Prisma.ApprovalItemWhereInput
}

export type ApprovalItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ApprovalItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApprovalItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ApprovalItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApprovalItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApprovalItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  approvalId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ApprovalItemCreateNestedManyWithoutApprovalInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutApprovalInput, Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput> | Prisma.ApprovalItemCreateWithoutApprovalInput[] | Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput | Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput[]
  createMany?: Prisma.ApprovalItemCreateManyApprovalInputEnvelope
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
}

export type ApprovalItemUncheckedCreateNestedManyWithoutApprovalInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutApprovalInput, Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput> | Prisma.ApprovalItemCreateWithoutApprovalInput[] | Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput | Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput[]
  createMany?: Prisma.ApprovalItemCreateManyApprovalInputEnvelope
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
}

export type ApprovalItemUpdateManyWithoutApprovalNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutApprovalInput, Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput> | Prisma.ApprovalItemCreateWithoutApprovalInput[] | Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput | Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput[]
  upsert?: Prisma.ApprovalItemUpsertWithWhereUniqueWithoutApprovalInput | Prisma.ApprovalItemUpsertWithWhereUniqueWithoutApprovalInput[]
  createMany?: Prisma.ApprovalItemCreateManyApprovalInputEnvelope
  set?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  disconnect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  delete?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  update?: Prisma.ApprovalItemUpdateWithWhereUniqueWithoutApprovalInput | Prisma.ApprovalItemUpdateWithWhereUniqueWithoutApprovalInput[]
  updateMany?: Prisma.ApprovalItemUpdateManyWithWhereWithoutApprovalInput | Prisma.ApprovalItemUpdateManyWithWhereWithoutApprovalInput[]
  deleteMany?: Prisma.ApprovalItemScalarWhereInput | Prisma.ApprovalItemScalarWhereInput[]
}

export type ApprovalItemUncheckedUpdateManyWithoutApprovalNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutApprovalInput, Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput> | Prisma.ApprovalItemCreateWithoutApprovalInput[] | Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput | Prisma.ApprovalItemCreateOrConnectWithoutApprovalInput[]
  upsert?: Prisma.ApprovalItemUpsertWithWhereUniqueWithoutApprovalInput | Prisma.ApprovalItemUpsertWithWhereUniqueWithoutApprovalInput[]
  createMany?: Prisma.ApprovalItemCreateManyApprovalInputEnvelope
  set?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  disconnect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  delete?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  update?: Prisma.ApprovalItemUpdateWithWhereUniqueWithoutApprovalInput | Prisma.ApprovalItemUpdateWithWhereUniqueWithoutApprovalInput[]
  updateMany?: Prisma.ApprovalItemUpdateManyWithWhereWithoutApprovalInput | Prisma.ApprovalItemUpdateManyWithWhereWithoutApprovalInput[]
  deleteMany?: Prisma.ApprovalItemScalarWhereInput | Prisma.ApprovalItemScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ApprovalItemCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutUserInput, Prisma.ApprovalItemUncheckedCreateWithoutUserInput> | Prisma.ApprovalItemCreateWithoutUserInput[] | Prisma.ApprovalItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutUserInput | Prisma.ApprovalItemCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ApprovalItemCreateManyUserInputEnvelope
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
}

export type ApprovalItemUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutUserInput, Prisma.ApprovalItemUncheckedCreateWithoutUserInput> | Prisma.ApprovalItemCreateWithoutUserInput[] | Prisma.ApprovalItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutUserInput | Prisma.ApprovalItemCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ApprovalItemCreateManyUserInputEnvelope
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
}

export type ApprovalItemUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutUserInput, Prisma.ApprovalItemUncheckedCreateWithoutUserInput> | Prisma.ApprovalItemCreateWithoutUserInput[] | Prisma.ApprovalItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutUserInput | Prisma.ApprovalItemCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ApprovalItemUpsertWithWhereUniqueWithoutUserInput | Prisma.ApprovalItemUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ApprovalItemCreateManyUserInputEnvelope
  set?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  disconnect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  delete?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  update?: Prisma.ApprovalItemUpdateWithWhereUniqueWithoutUserInput | Prisma.ApprovalItemUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ApprovalItemUpdateManyWithWhereWithoutUserInput | Prisma.ApprovalItemUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ApprovalItemScalarWhereInput | Prisma.ApprovalItemScalarWhereInput[]
}

export type ApprovalItemUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalItemCreateWithoutUserInput, Prisma.ApprovalItemUncheckedCreateWithoutUserInput> | Prisma.ApprovalItemCreateWithoutUserInput[] | Prisma.ApprovalItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ApprovalItemCreateOrConnectWithoutUserInput | Prisma.ApprovalItemCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ApprovalItemUpsertWithWhereUniqueWithoutUserInput | Prisma.ApprovalItemUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ApprovalItemCreateManyUserInputEnvelope
  set?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  disconnect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  delete?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  connect?: Prisma.ApprovalItemWhereUniqueInput | Prisma.ApprovalItemWhereUniqueInput[]
  update?: Prisma.ApprovalItemUpdateWithWhereUniqueWithoutUserInput | Prisma.ApprovalItemUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ApprovalItemUpdateManyWithWhereWithoutUserInput | Prisma.ApprovalItemUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ApprovalItemScalarWhereInput | Prisma.ApprovalItemScalarWhereInput[]
}

export type ApprovalItemCreateWithoutApprovalInput = {
  order: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutApprovalItemsInput
}

export type ApprovalItemUncheckedCreateWithoutApprovalInput = {
  id?: number
  order: number
  userId: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ApprovalItemCreateOrConnectWithoutApprovalInput = {
  where: Prisma.ApprovalItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ApprovalItemCreateWithoutApprovalInput, Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput>
}

export type ApprovalItemCreateManyApprovalInputEnvelope = {
  data: Prisma.ApprovalItemCreateManyApprovalInput | Prisma.ApprovalItemCreateManyApprovalInput[]
  skipDuplicates?: boolean
}

export type ApprovalItemUpsertWithWhereUniqueWithoutApprovalInput = {
  where: Prisma.ApprovalItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ApprovalItemUpdateWithoutApprovalInput, Prisma.ApprovalItemUncheckedUpdateWithoutApprovalInput>
  create: Prisma.XOR<Prisma.ApprovalItemCreateWithoutApprovalInput, Prisma.ApprovalItemUncheckedCreateWithoutApprovalInput>
}

export type ApprovalItemUpdateWithWhereUniqueWithoutApprovalInput = {
  where: Prisma.ApprovalItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ApprovalItemUpdateWithoutApprovalInput, Prisma.ApprovalItemUncheckedUpdateWithoutApprovalInput>
}

export type ApprovalItemUpdateManyWithWhereWithoutApprovalInput = {
  where: Prisma.ApprovalItemScalarWhereInput
  data: Prisma.XOR<Prisma.ApprovalItemUpdateManyMutationInput, Prisma.ApprovalItemUncheckedUpdateManyWithoutApprovalInput>
}

export type ApprovalItemScalarWhereInput = {
  AND?: Prisma.ApprovalItemScalarWhereInput | Prisma.ApprovalItemScalarWhereInput[]
  OR?: Prisma.ApprovalItemScalarWhereInput[]
  NOT?: Prisma.ApprovalItemScalarWhereInput | Prisma.ApprovalItemScalarWhereInput[]
  id?: Prisma.IntFilter<"ApprovalItem"> | number
  approvalId?: Prisma.IntNullableFilter<"ApprovalItem"> | number | null
  order?: Prisma.IntFilter<"ApprovalItem"> | number
  userId?: Prisma.IntFilter<"ApprovalItem"> | number
  status?: Prisma.EnumApprovalStatusNullableFilter<"ApprovalItem"> | $Enums.ApprovalStatus | null
  remarks?: Prisma.StringNullableFilter<"ApprovalItem"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ApprovalItem"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"ApprovalItem"> | Date | string | null
}

export type ApprovalItemCreateWithoutUserInput = {
  order: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  approval?: Prisma.ApprovalCreateNestedOneWithoutItemsInput
}

export type ApprovalItemUncheckedCreateWithoutUserInput = {
  id?: number
  approvalId?: number | null
  order: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ApprovalItemCreateOrConnectWithoutUserInput = {
  where: Prisma.ApprovalItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ApprovalItemCreateWithoutUserInput, Prisma.ApprovalItemUncheckedCreateWithoutUserInput>
}

export type ApprovalItemCreateManyUserInputEnvelope = {
  data: Prisma.ApprovalItemCreateManyUserInput | Prisma.ApprovalItemCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ApprovalItemUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ApprovalItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ApprovalItemUpdateWithoutUserInput, Prisma.ApprovalItemUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ApprovalItemCreateWithoutUserInput, Prisma.ApprovalItemUncheckedCreateWithoutUserInput>
}

export type ApprovalItemUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ApprovalItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ApprovalItemUpdateWithoutUserInput, Prisma.ApprovalItemUncheckedUpdateWithoutUserInput>
}

export type ApprovalItemUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ApprovalItemScalarWhereInput
  data: Prisma.XOR<Prisma.ApprovalItemUpdateManyMutationInput, Prisma.ApprovalItemUncheckedUpdateManyWithoutUserInput>
}

export type ApprovalItemCreateManyApprovalInput = {
  id?: number
  order: number
  userId: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ApprovalItemUpdateWithoutApprovalInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutApprovalItemsNestedInput
}

export type ApprovalItemUncheckedUpdateWithoutApprovalInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApprovalItemUncheckedUpdateManyWithoutApprovalInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApprovalItemCreateManyUserInput = {
  id?: number
  approvalId?: number | null
  order: number
  status?: $Enums.ApprovalStatus | null
  remarks?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type ApprovalItemUpdateWithoutUserInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approval?: Prisma.ApprovalUpdateOneWithoutItemsNestedInput
}

export type ApprovalItemUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  approvalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApprovalItemUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  approvalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.NullableEnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus | null
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type ApprovalItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  approvalId?: boolean
  order?: boolean
  userId?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  approval?: boolean | Prisma.ApprovalItem$approvalArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalItem"]>

export type ApprovalItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  approvalId?: boolean
  order?: boolean
  userId?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  approval?: boolean | Prisma.ApprovalItem$approvalArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalItem"]>

export type ApprovalItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  approvalId?: boolean
  order?: boolean
  userId?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  approval?: boolean | Prisma.ApprovalItem$approvalArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalItem"]>

export type ApprovalItemSelectScalar = {
  id?: boolean
  approvalId?: boolean
  order?: boolean
  userId?: boolean
  status?: boolean
  remarks?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ApprovalItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "approvalId" | "order" | "userId" | "status" | "remarks" | "createdAt" | "updatedAt", ExtArgs["result"]["approvalItem"]>
export type ApprovalItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  approval?: boolean | Prisma.ApprovalItem$approvalArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ApprovalItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  approval?: boolean | Prisma.ApprovalItem$approvalArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ApprovalItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  approval?: boolean | Prisma.ApprovalItem$approvalArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ApprovalItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApprovalItem"
  objects: {
    approval: Prisma.$ApprovalPayload<ExtArgs> | null
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    approvalId: number | null
    order: number
    userId: number
    status: $Enums.ApprovalStatus | null
    remarks: string | null
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["approvalItem"]>
  composites: {}
}

export type ApprovalItemGetPayload<S extends boolean | null | undefined | ApprovalItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload, S>

export type ApprovalItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApprovalItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApprovalItemCountAggregateInputType | true
  }

export interface ApprovalItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApprovalItem'], meta: { name: 'ApprovalItem' } }
  /**
   * Find zero or one ApprovalItem that matches the filter.
   * @param {ApprovalItemFindUniqueArgs} args - Arguments to find a ApprovalItem
   * @example
   * // Get one ApprovalItem
   * const approvalItem = await prisma.approvalItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApprovalItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ApprovalItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApprovalItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApprovalItemFindUniqueOrThrowArgs} args - Arguments to find a ApprovalItem
   * @example
   * // Get one ApprovalItem
   * const approvalItem = await prisma.approvalItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApprovalItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApprovalItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApprovalItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemFindFirstArgs} args - Arguments to find a ApprovalItem
   * @example
   * // Get one ApprovalItem
   * const approvalItem = await prisma.approvalItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApprovalItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ApprovalItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApprovalItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemFindFirstOrThrowArgs} args - Arguments to find a ApprovalItem
   * @example
   * // Get one ApprovalItem
   * const approvalItem = await prisma.approvalItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApprovalItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApprovalItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApprovalItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApprovalItems
   * const approvalItems = await prisma.approvalItem.findMany()
   * 
   * // Get first 10 ApprovalItems
   * const approvalItems = await prisma.approvalItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const approvalItemWithIdOnly = await prisma.approvalItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApprovalItemFindManyArgs>(args?: Prisma.SelectSubset<T, ApprovalItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApprovalItem.
   * @param {ApprovalItemCreateArgs} args - Arguments to create a ApprovalItem.
   * @example
   * // Create one ApprovalItem
   * const ApprovalItem = await prisma.approvalItem.create({
   *   data: {
   *     // ... data to create a ApprovalItem
   *   }
   * })
   * 
   */
  create<T extends ApprovalItemCreateArgs>(args: Prisma.SelectSubset<T, ApprovalItemCreateArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApprovalItems.
   * @param {ApprovalItemCreateManyArgs} args - Arguments to create many ApprovalItems.
   * @example
   * // Create many ApprovalItems
   * const approvalItem = await prisma.approvalItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApprovalItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ApprovalItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApprovalItems and returns the data saved in the database.
   * @param {ApprovalItemCreateManyAndReturnArgs} args - Arguments to create many ApprovalItems.
   * @example
   * // Create many ApprovalItems
   * const approvalItem = await prisma.approvalItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApprovalItems and only return the `id`
   * const approvalItemWithIdOnly = await prisma.approvalItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApprovalItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApprovalItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApprovalItem.
   * @param {ApprovalItemDeleteArgs} args - Arguments to delete one ApprovalItem.
   * @example
   * // Delete one ApprovalItem
   * const ApprovalItem = await prisma.approvalItem.delete({
   *   where: {
   *     // ... filter to delete one ApprovalItem
   *   }
   * })
   * 
   */
  delete<T extends ApprovalItemDeleteArgs>(args: Prisma.SelectSubset<T, ApprovalItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApprovalItem.
   * @param {ApprovalItemUpdateArgs} args - Arguments to update one ApprovalItem.
   * @example
   * // Update one ApprovalItem
   * const approvalItem = await prisma.approvalItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApprovalItemUpdateArgs>(args: Prisma.SelectSubset<T, ApprovalItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApprovalItems.
   * @param {ApprovalItemDeleteManyArgs} args - Arguments to filter ApprovalItems to delete.
   * @example
   * // Delete a few ApprovalItems
   * const { count } = await prisma.approvalItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApprovalItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApprovalItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApprovalItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApprovalItems
   * const approvalItem = await prisma.approvalItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApprovalItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ApprovalItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApprovalItems and returns the data updated in the database.
   * @param {ApprovalItemUpdateManyAndReturnArgs} args - Arguments to update many ApprovalItems.
   * @example
   * // Update many ApprovalItems
   * const approvalItem = await prisma.approvalItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApprovalItems and only return the `id`
   * const approvalItemWithIdOnly = await prisma.approvalItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApprovalItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApprovalItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApprovalItem.
   * @param {ApprovalItemUpsertArgs} args - Arguments to update or create a ApprovalItem.
   * @example
   * // Update or create a ApprovalItem
   * const approvalItem = await prisma.approvalItem.upsert({
   *   create: {
   *     // ... data to create a ApprovalItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApprovalItem we want to update
   *   }
   * })
   */
  upsert<T extends ApprovalItemUpsertArgs>(args: Prisma.SelectSubset<T, ApprovalItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ApprovalItemClient<runtime.Types.Result.GetResult<Prisma.$ApprovalItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApprovalItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemCountArgs} args - Arguments to filter ApprovalItems to count.
   * @example
   * // Count the number of ApprovalItems
   * const count = await prisma.approvalItem.count({
   *   where: {
   *     // ... the filter for the ApprovalItems we want to count
   *   }
   * })
  **/
  count<T extends ApprovalItemCountArgs>(
    args?: Prisma.Subset<T, ApprovalItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApprovalItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApprovalItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApprovalItemAggregateArgs>(args: Prisma.Subset<T, ApprovalItemAggregateArgs>): Prisma.PrismaPromise<GetApprovalItemAggregateType<T>>

  /**
   * Group by ApprovalItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApprovalItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApprovalItemGroupByArgs['orderBy'] }
      : { orderBy?: ApprovalItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApprovalItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApprovalItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApprovalItem model
 */
readonly fields: ApprovalItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApprovalItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApprovalItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  approval<T extends Prisma.ApprovalItem$approvalArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApprovalItem$approvalArgs<ExtArgs>>): Prisma.Prisma__ApprovalClient<runtime.Types.Result.GetResult<Prisma.$ApprovalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApprovalItem model
 */
export interface ApprovalItemFieldRefs {
  readonly id: Prisma.FieldRef<"ApprovalItem", 'Int'>
  readonly approvalId: Prisma.FieldRef<"ApprovalItem", 'Int'>
  readonly order: Prisma.FieldRef<"ApprovalItem", 'Int'>
  readonly userId: Prisma.FieldRef<"ApprovalItem", 'Int'>
  readonly status: Prisma.FieldRef<"ApprovalItem", 'ApprovalStatus'>
  readonly remarks: Prisma.FieldRef<"ApprovalItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"ApprovalItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ApprovalItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ApprovalItem findUnique
 */
export type ApprovalItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalItem to fetch.
   */
  where: Prisma.ApprovalItemWhereUniqueInput
}

/**
 * ApprovalItem findUniqueOrThrow
 */
export type ApprovalItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalItem to fetch.
   */
  where: Prisma.ApprovalItemWhereUniqueInput
}

/**
 * ApprovalItem findFirst
 */
export type ApprovalItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalItem to fetch.
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalItems to fetch.
   */
  orderBy?: Prisma.ApprovalItemOrderByWithRelationInput | Prisma.ApprovalItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApprovalItems.
   */
  cursor?: Prisma.ApprovalItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalItems.
   */
  distinct?: Prisma.ApprovalItemScalarFieldEnum | Prisma.ApprovalItemScalarFieldEnum[]
}

/**
 * ApprovalItem findFirstOrThrow
 */
export type ApprovalItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalItem to fetch.
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalItems to fetch.
   */
  orderBy?: Prisma.ApprovalItemOrderByWithRelationInput | Prisma.ApprovalItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApprovalItems.
   */
  cursor?: Prisma.ApprovalItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalItems.
   */
  distinct?: Prisma.ApprovalItemScalarFieldEnum | Prisma.ApprovalItemScalarFieldEnum[]
}

/**
 * ApprovalItem findMany
 */
export type ApprovalItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalItems to fetch.
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalItems to fetch.
   */
  orderBy?: Prisma.ApprovalItemOrderByWithRelationInput | Prisma.ApprovalItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApprovalItems.
   */
  cursor?: Prisma.ApprovalItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalItems.
   */
  distinct?: Prisma.ApprovalItemScalarFieldEnum | Prisma.ApprovalItemScalarFieldEnum[]
}

/**
 * ApprovalItem create
 */
export type ApprovalItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * The data needed to create a ApprovalItem.
   */
  data: Prisma.XOR<Prisma.ApprovalItemCreateInput, Prisma.ApprovalItemUncheckedCreateInput>
}

/**
 * ApprovalItem createMany
 */
export type ApprovalItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApprovalItems.
   */
  data: Prisma.ApprovalItemCreateManyInput | Prisma.ApprovalItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApprovalItem createManyAndReturn
 */
export type ApprovalItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * The data used to create many ApprovalItems.
   */
  data: Prisma.ApprovalItemCreateManyInput | Prisma.ApprovalItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ApprovalItem update
 */
export type ApprovalItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * The data needed to update a ApprovalItem.
   */
  data: Prisma.XOR<Prisma.ApprovalItemUpdateInput, Prisma.ApprovalItemUncheckedUpdateInput>
  /**
   * Choose, which ApprovalItem to update.
   */
  where: Prisma.ApprovalItemWhereUniqueInput
}

/**
 * ApprovalItem updateMany
 */
export type ApprovalItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApprovalItems.
   */
  data: Prisma.XOR<Prisma.ApprovalItemUpdateManyMutationInput, Prisma.ApprovalItemUncheckedUpdateManyInput>
  /**
   * Filter which ApprovalItems to update
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * Limit how many ApprovalItems to update.
   */
  limit?: number
}

/**
 * ApprovalItem updateManyAndReturn
 */
export type ApprovalItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * The data used to update ApprovalItems.
   */
  data: Prisma.XOR<Prisma.ApprovalItemUpdateManyMutationInput, Prisma.ApprovalItemUncheckedUpdateManyInput>
  /**
   * Filter which ApprovalItems to update
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * Limit how many ApprovalItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ApprovalItem upsert
 */
export type ApprovalItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * The filter to search for the ApprovalItem to update in case it exists.
   */
  where: Prisma.ApprovalItemWhereUniqueInput
  /**
   * In case the ApprovalItem found by the `where` argument doesn't exist, create a new ApprovalItem with this data.
   */
  create: Prisma.XOR<Prisma.ApprovalItemCreateInput, Prisma.ApprovalItemUncheckedCreateInput>
  /**
   * In case the ApprovalItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApprovalItemUpdateInput, Prisma.ApprovalItemUncheckedUpdateInput>
}

/**
 * ApprovalItem delete
 */
export type ApprovalItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
  /**
   * Filter which ApprovalItem to delete.
   */
  where: Prisma.ApprovalItemWhereUniqueInput
}

/**
 * ApprovalItem deleteMany
 */
export type ApprovalItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApprovalItems to delete
   */
  where?: Prisma.ApprovalItemWhereInput
  /**
   * Limit how many ApprovalItems to delete.
   */
  limit?: number
}

/**
 * ApprovalItem.approval
 */
export type ApprovalItem$approvalArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Approval
   */
  select?: Prisma.ApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Approval
   */
  omit?: Prisma.ApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalInclude<ExtArgs> | null
  where?: Prisma.ApprovalWhereInput
}

/**
 * ApprovalItem without action
 */
export type ApprovalItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalItem
   */
  select?: Prisma.ApprovalItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalItem
   */
  omit?: Prisma.ApprovalItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalItemInclude<ExtArgs> | null
}
