
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Company` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Company
 * 
 */
export type CompanyModel = runtime.Types.Result.DefaultSelection<Prisma.$CompanyPayload>

export type AggregateCompany = {
  _count: CompanyCountAggregateOutputType | null
  _avg: CompanyAvgAggregateOutputType | null
  _sum: CompanySumAggregateOutputType | null
  _min: CompanyMinAggregateOutputType | null
  _max: CompanyMaxAggregateOutputType | null
}

export type CompanyAvgAggregateOutputType = {
  id: number | null
}

export type CompanySumAggregateOutputType = {
  id: number | null
}

export type CompanyMinAggregateOutputType = {
  id: number | null
  code: string | null
  name: string | null
  isDefault: boolean | null
}

export type CompanyMaxAggregateOutputType = {
  id: number | null
  code: string | null
  name: string | null
  isDefault: boolean | null
}

export type CompanyCountAggregateOutputType = {
  id: number
  code: number
  name: number
  isDefault: number
  _all: number
}


export type CompanyAvgAggregateInputType = {
  id?: true
}

export type CompanySumAggregateInputType = {
  id?: true
}

export type CompanyMinAggregateInputType = {
  id?: true
  code?: true
  name?: true
  isDefault?: true
}

export type CompanyMaxAggregateInputType = {
  id?: true
  code?: true
  name?: true
  isDefault?: true
}

export type CompanyCountAggregateInputType = {
  id?: true
  code?: true
  name?: true
  isDefault?: true
  _all?: true
}

export type CompanyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Company to aggregate.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Companies
  **/
  _count?: true | CompanyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CompanyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CompanySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CompanyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CompanyMaxAggregateInputType
}

export type GetCompanyAggregateType<T extends CompanyAggregateArgs> = {
      [P in keyof T & keyof AggregateCompany]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCompany[P]>
    : Prisma.GetScalarType<T[P], AggregateCompany[P]>
}




export type CompanyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompanyWhereInput
  orderBy?: Prisma.CompanyOrderByWithAggregationInput | Prisma.CompanyOrderByWithAggregationInput[]
  by: Prisma.CompanyScalarFieldEnum[] | Prisma.CompanyScalarFieldEnum
  having?: Prisma.CompanyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CompanyCountAggregateInputType | true
  _avg?: CompanyAvgAggregateInputType
  _sum?: CompanySumAggregateInputType
  _min?: CompanyMinAggregateInputType
  _max?: CompanyMaxAggregateInputType
}

export type CompanyGroupByOutputType = {
  id: number
  code: string
  name: string
  isDefault: boolean
  _count: CompanyCountAggregateOutputType | null
  _avg: CompanyAvgAggregateOutputType | null
  _sum: CompanySumAggregateOutputType | null
  _min: CompanyMinAggregateOutputType | null
  _max: CompanyMaxAggregateOutputType | null
}

export type GetCompanyGroupByPayload<T extends CompanyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CompanyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CompanyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CompanyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CompanyGroupByOutputType[P]>
      }
    >
  >



export type CompanyWhereInput = {
  AND?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  OR?: Prisma.CompanyWhereInput[]
  NOT?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  id?: Prisma.IntFilter<"Company"> | number
  code?: Prisma.StringFilter<"Company"> | string
  name?: Prisma.StringFilter<"Company"> | string
  isDefault?: Prisma.BoolFilter<"Company"> | boolean
  Nkp?: Prisma.NkpListRelationFilter
  ApprovalSetting?: Prisma.ApprovalSettingListRelationFilter
  Opportunity?: Prisma.OpportunityListRelationFilter
  Lead?: Prisma.LeadListRelationFilter
}

export type CompanyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDefault?: Prisma.SortOrder
  Nkp?: Prisma.NkpOrderByRelationAggregateInput
  ApprovalSetting?: Prisma.ApprovalSettingOrderByRelationAggregateInput
  Opportunity?: Prisma.OpportunityOrderByRelationAggregateInput
  Lead?: Prisma.LeadOrderByRelationAggregateInput
}

export type CompanyWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  code?: string
  AND?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  OR?: Prisma.CompanyWhereInput[]
  NOT?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  name?: Prisma.StringFilter<"Company"> | string
  isDefault?: Prisma.BoolFilter<"Company"> | boolean
  Nkp?: Prisma.NkpListRelationFilter
  ApprovalSetting?: Prisma.ApprovalSettingListRelationFilter
  Opportunity?: Prisma.OpportunityListRelationFilter
  Lead?: Prisma.LeadListRelationFilter
}, "id" | "code">

export type CompanyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDefault?: Prisma.SortOrder
  _count?: Prisma.CompanyCountOrderByAggregateInput
  _avg?: Prisma.CompanyAvgOrderByAggregateInput
  _max?: Prisma.CompanyMaxOrderByAggregateInput
  _min?: Prisma.CompanyMinOrderByAggregateInput
  _sum?: Prisma.CompanySumOrderByAggregateInput
}

export type CompanyScalarWhereWithAggregatesInput = {
  AND?: Prisma.CompanyScalarWhereWithAggregatesInput | Prisma.CompanyScalarWhereWithAggregatesInput[]
  OR?: Prisma.CompanyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CompanyScalarWhereWithAggregatesInput | Prisma.CompanyScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Company"> | number
  code?: Prisma.StringWithAggregatesFilter<"Company"> | string
  name?: Prisma.StringWithAggregatesFilter<"Company"> | string
  isDefault?: Prisma.BoolWithAggregatesFilter<"Company"> | boolean
}

export type CompanyCreateInput = {
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpCreateNestedManyWithoutCompanyInput
  ApprovalSetting?: Prisma.ApprovalSettingCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadCreateNestedManyWithoutCompanyInput
}

export type CompanyUncheckedCreateInput = {
  id?: number
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpUncheckedCreateNestedManyWithoutCompanyInput
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityUncheckedCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadUncheckedCreateNestedManyWithoutCompanyInput
}

export type CompanyUpdateInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUpdateManyWithoutCompanyNestedInput
  ApprovalSetting?: Prisma.ApprovalSettingUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUpdateManyWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUncheckedUpdateManyWithoutCompanyNestedInput
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUncheckedUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUncheckedUpdateManyWithoutCompanyNestedInput
}

export type CompanyCreateManyInput = {
  id?: number
  code: string
  name: string
  isDefault?: boolean
}

export type CompanyUpdateManyMutationInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CompanyUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CompanyScalarRelationFilter = {
  is?: Prisma.CompanyWhereInput
  isNot?: Prisma.CompanyWhereInput
}

export type CompanyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDefault?: Prisma.SortOrder
}

export type CompanyAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CompanyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDefault?: Prisma.SortOrder
}

export type CompanyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDefault?: Prisma.SortOrder
}

export type CompanySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CompanyCreateNestedOneWithoutLeadInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutLeadInput, Prisma.CompanyUncheckedCreateWithoutLeadInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutLeadInput
  connect?: Prisma.CompanyWhereUniqueInput
}

export type CompanyUpdateOneRequiredWithoutLeadNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutLeadInput, Prisma.CompanyUncheckedCreateWithoutLeadInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutLeadInput
  upsert?: Prisma.CompanyUpsertWithoutLeadInput
  connect?: Prisma.CompanyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompanyUpdateToOneWithWhereWithoutLeadInput, Prisma.CompanyUpdateWithoutLeadInput>, Prisma.CompanyUncheckedUpdateWithoutLeadInput>
}

export type CompanyCreateNestedOneWithoutOpportunityInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutOpportunityInput, Prisma.CompanyUncheckedCreateWithoutOpportunityInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutOpportunityInput
  connect?: Prisma.CompanyWhereUniqueInput
}

export type CompanyUpdateOneRequiredWithoutOpportunityNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutOpportunityInput, Prisma.CompanyUncheckedCreateWithoutOpportunityInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutOpportunityInput
  upsert?: Prisma.CompanyUpsertWithoutOpportunityInput
  connect?: Prisma.CompanyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompanyUpdateToOneWithWhereWithoutOpportunityInput, Prisma.CompanyUpdateWithoutOpportunityInput>, Prisma.CompanyUncheckedUpdateWithoutOpportunityInput>
}

export type CompanyCreateNestedOneWithoutNkpInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutNkpInput, Prisma.CompanyUncheckedCreateWithoutNkpInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutNkpInput
  connect?: Prisma.CompanyWhereUniqueInput
}

export type CompanyUpdateOneRequiredWithoutNkpNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutNkpInput, Prisma.CompanyUncheckedCreateWithoutNkpInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutNkpInput
  upsert?: Prisma.CompanyUpsertWithoutNkpInput
  connect?: Prisma.CompanyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompanyUpdateToOneWithWhereWithoutNkpInput, Prisma.CompanyUpdateWithoutNkpInput>, Prisma.CompanyUncheckedUpdateWithoutNkpInput>
}

export type CompanyCreateNestedOneWithoutApprovalSettingInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutApprovalSettingInput, Prisma.CompanyUncheckedCreateWithoutApprovalSettingInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutApprovalSettingInput
  connect?: Prisma.CompanyWhereUniqueInput
}

export type CompanyUpdateOneRequiredWithoutApprovalSettingNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutApprovalSettingInput, Prisma.CompanyUncheckedCreateWithoutApprovalSettingInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutApprovalSettingInput
  upsert?: Prisma.CompanyUpsertWithoutApprovalSettingInput
  connect?: Prisma.CompanyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompanyUpdateToOneWithWhereWithoutApprovalSettingInput, Prisma.CompanyUpdateWithoutApprovalSettingInput>, Prisma.CompanyUncheckedUpdateWithoutApprovalSettingInput>
}

export type CompanyCreateWithoutLeadInput = {
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpCreateNestedManyWithoutCompanyInput
  ApprovalSetting?: Prisma.ApprovalSettingCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityCreateNestedManyWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutLeadInput = {
  id?: number
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpUncheckedCreateNestedManyWithoutCompanyInput
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityUncheckedCreateNestedManyWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutLeadInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutLeadInput, Prisma.CompanyUncheckedCreateWithoutLeadInput>
}

export type CompanyUpsertWithoutLeadInput = {
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutLeadInput, Prisma.CompanyUncheckedUpdateWithoutLeadInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutLeadInput, Prisma.CompanyUncheckedCreateWithoutLeadInput>
  where?: Prisma.CompanyWhereInput
}

export type CompanyUpdateToOneWithWhereWithoutLeadInput = {
  where?: Prisma.CompanyWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutLeadInput, Prisma.CompanyUncheckedUpdateWithoutLeadInput>
}

export type CompanyUpdateWithoutLeadInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUpdateManyWithoutCompanyNestedInput
  ApprovalSetting?: Prisma.ApprovalSettingUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUpdateManyWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutLeadInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUncheckedUpdateManyWithoutCompanyNestedInput
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUncheckedUpdateManyWithoutCompanyNestedInput
}

export type CompanyCreateWithoutOpportunityInput = {
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpCreateNestedManyWithoutCompanyInput
  ApprovalSetting?: Prisma.ApprovalSettingCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadCreateNestedManyWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutOpportunityInput = {
  id?: number
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpUncheckedCreateNestedManyWithoutCompanyInput
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadUncheckedCreateNestedManyWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutOpportunityInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutOpportunityInput, Prisma.CompanyUncheckedCreateWithoutOpportunityInput>
}

export type CompanyUpsertWithoutOpportunityInput = {
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutOpportunityInput, Prisma.CompanyUncheckedUpdateWithoutOpportunityInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutOpportunityInput, Prisma.CompanyUncheckedCreateWithoutOpportunityInput>
  where?: Prisma.CompanyWhereInput
}

export type CompanyUpdateToOneWithWhereWithoutOpportunityInput = {
  where?: Prisma.CompanyWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutOpportunityInput, Prisma.CompanyUncheckedUpdateWithoutOpportunityInput>
}

export type CompanyUpdateWithoutOpportunityInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUpdateManyWithoutCompanyNestedInput
  ApprovalSetting?: Prisma.ApprovalSettingUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUpdateManyWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutOpportunityInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUncheckedUpdateManyWithoutCompanyNestedInput
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUncheckedUpdateManyWithoutCompanyNestedInput
}

export type CompanyCreateWithoutNkpInput = {
  code: string
  name: string
  isDefault?: boolean
  ApprovalSetting?: Prisma.ApprovalSettingCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadCreateNestedManyWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutNkpInput = {
  id?: number
  code: string
  name: string
  isDefault?: boolean
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityUncheckedCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadUncheckedCreateNestedManyWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutNkpInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutNkpInput, Prisma.CompanyUncheckedCreateWithoutNkpInput>
}

export type CompanyUpsertWithoutNkpInput = {
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutNkpInput, Prisma.CompanyUncheckedUpdateWithoutNkpInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutNkpInput, Prisma.CompanyUncheckedCreateWithoutNkpInput>
  where?: Prisma.CompanyWhereInput
}

export type CompanyUpdateToOneWithWhereWithoutNkpInput = {
  where?: Prisma.CompanyWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutNkpInput, Prisma.CompanyUncheckedUpdateWithoutNkpInput>
}

export type CompanyUpdateWithoutNkpInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ApprovalSetting?: Prisma.ApprovalSettingUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUpdateManyWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutNkpInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ApprovalSetting?: Prisma.ApprovalSettingUncheckedUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUncheckedUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUncheckedUpdateManyWithoutCompanyNestedInput
}

export type CompanyCreateWithoutApprovalSettingInput = {
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadCreateNestedManyWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutApprovalSettingInput = {
  id?: number
  code: string
  name: string
  isDefault?: boolean
  Nkp?: Prisma.NkpUncheckedCreateNestedManyWithoutCompanyInput
  Opportunity?: Prisma.OpportunityUncheckedCreateNestedManyWithoutCompanyInput
  Lead?: Prisma.LeadUncheckedCreateNestedManyWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutApprovalSettingInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutApprovalSettingInput, Prisma.CompanyUncheckedCreateWithoutApprovalSettingInput>
}

export type CompanyUpsertWithoutApprovalSettingInput = {
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutApprovalSettingInput, Prisma.CompanyUncheckedUpdateWithoutApprovalSettingInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutApprovalSettingInput, Prisma.CompanyUncheckedCreateWithoutApprovalSettingInput>
  where?: Prisma.CompanyWhereInput
}

export type CompanyUpdateToOneWithWhereWithoutApprovalSettingInput = {
  where?: Prisma.CompanyWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutApprovalSettingInput, Prisma.CompanyUncheckedUpdateWithoutApprovalSettingInput>
}

export type CompanyUpdateWithoutApprovalSettingInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUpdateManyWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutApprovalSettingInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Nkp?: Prisma.NkpUncheckedUpdateManyWithoutCompanyNestedInput
  Opportunity?: Prisma.OpportunityUncheckedUpdateManyWithoutCompanyNestedInput
  Lead?: Prisma.LeadUncheckedUpdateManyWithoutCompanyNestedInput
}


/**
 * Count Type CompanyCountOutputType
 */

export type CompanyCountOutputType = {
  Nkp: number
  ApprovalSetting: number
  Opportunity: number
  Lead: number
}

export type CompanyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Nkp?: boolean | CompanyCountOutputTypeCountNkpArgs
  ApprovalSetting?: boolean | CompanyCountOutputTypeCountApprovalSettingArgs
  Opportunity?: boolean | CompanyCountOutputTypeCountOpportunityArgs
  Lead?: boolean | CompanyCountOutputTypeCountLeadArgs
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompanyCountOutputType
   */
  select?: Prisma.CompanyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeCountNkpArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NkpWhereInput
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeCountApprovalSettingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApprovalSettingWhereInput
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeCountOpportunityArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OpportunityWhereInput
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeCountLeadArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeadWhereInput
}


export type CompanySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  isDefault?: boolean
  Nkp?: boolean | Prisma.Company$NkpArgs<ExtArgs>
  ApprovalSetting?: boolean | Prisma.Company$ApprovalSettingArgs<ExtArgs>
  Opportunity?: boolean | Prisma.Company$OpportunityArgs<ExtArgs>
  Lead?: boolean | Prisma.Company$LeadArgs<ExtArgs>
  _count?: boolean | Prisma.CompanyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["company"]>

export type CompanySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  isDefault?: boolean
}, ExtArgs["result"]["company"]>

export type CompanySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  isDefault?: boolean
}, ExtArgs["result"]["company"]>

export type CompanySelectScalar = {
  id?: boolean
  code?: boolean
  name?: boolean
  isDefault?: boolean
}

export type CompanyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "name" | "isDefault", ExtArgs["result"]["company"]>
export type CompanyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Nkp?: boolean | Prisma.Company$NkpArgs<ExtArgs>
  ApprovalSetting?: boolean | Prisma.Company$ApprovalSettingArgs<ExtArgs>
  Opportunity?: boolean | Prisma.Company$OpportunityArgs<ExtArgs>
  Lead?: boolean | Prisma.Company$LeadArgs<ExtArgs>
  _count?: boolean | Prisma.CompanyCountOutputTypeDefaultArgs<ExtArgs>
}
export type CompanyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CompanyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CompanyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Company"
  objects: {
    Nkp: Prisma.$NkpPayload<ExtArgs>[]
    ApprovalSetting: Prisma.$ApprovalSettingPayload<ExtArgs>[]
    Opportunity: Prisma.$OpportunityPayload<ExtArgs>[]
    Lead: Prisma.$LeadPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    code: string
    name: string
    isDefault: boolean
  }, ExtArgs["result"]["company"]>
  composites: {}
}

export type CompanyGetPayload<S extends boolean | null | undefined | CompanyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CompanyPayload, S>

export type CompanyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CompanyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CompanyCountAggregateInputType | true
  }

export interface CompanyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Company'], meta: { name: 'Company' } }
  /**
   * Find zero or one Company that matches the filter.
   * @param {CompanyFindUniqueArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CompanyFindUniqueArgs>(args: Prisma.SelectSubset<T, CompanyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Company that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CompanyFindUniqueOrThrowArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CompanyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CompanyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Company that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyFindFirstArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CompanyFindFirstArgs>(args?: Prisma.SelectSubset<T, CompanyFindFirstArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Company that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyFindFirstOrThrowArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CompanyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CompanyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Companies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Companies
   * const companies = await prisma.company.findMany()
   * 
   * // Get first 10 Companies
   * const companies = await prisma.company.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const companyWithIdOnly = await prisma.company.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CompanyFindManyArgs>(args?: Prisma.SelectSubset<T, CompanyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Company.
   * @param {CompanyCreateArgs} args - Arguments to create a Company.
   * @example
   * // Create one Company
   * const Company = await prisma.company.create({
   *   data: {
   *     // ... data to create a Company
   *   }
   * })
   * 
   */
  create<T extends CompanyCreateArgs>(args: Prisma.SelectSubset<T, CompanyCreateArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Companies.
   * @param {CompanyCreateManyArgs} args - Arguments to create many Companies.
   * @example
   * // Create many Companies
   * const company = await prisma.company.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CompanyCreateManyArgs>(args?: Prisma.SelectSubset<T, CompanyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Companies and returns the data saved in the database.
   * @param {CompanyCreateManyAndReturnArgs} args - Arguments to create many Companies.
   * @example
   * // Create many Companies
   * const company = await prisma.company.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Companies and only return the `id`
   * const companyWithIdOnly = await prisma.company.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CompanyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CompanyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Company.
   * @param {CompanyDeleteArgs} args - Arguments to delete one Company.
   * @example
   * // Delete one Company
   * const Company = await prisma.company.delete({
   *   where: {
   *     // ... filter to delete one Company
   *   }
   * })
   * 
   */
  delete<T extends CompanyDeleteArgs>(args: Prisma.SelectSubset<T, CompanyDeleteArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Company.
   * @param {CompanyUpdateArgs} args - Arguments to update one Company.
   * @example
   * // Update one Company
   * const company = await prisma.company.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CompanyUpdateArgs>(args: Prisma.SelectSubset<T, CompanyUpdateArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Companies.
   * @param {CompanyDeleteManyArgs} args - Arguments to filter Companies to delete.
   * @example
   * // Delete a few Companies
   * const { count } = await prisma.company.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CompanyDeleteManyArgs>(args?: Prisma.SelectSubset<T, CompanyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Companies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Companies
   * const company = await prisma.company.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CompanyUpdateManyArgs>(args: Prisma.SelectSubset<T, CompanyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Companies and returns the data updated in the database.
   * @param {CompanyUpdateManyAndReturnArgs} args - Arguments to update many Companies.
   * @example
   * // Update many Companies
   * const company = await prisma.company.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Companies and only return the `id`
   * const companyWithIdOnly = await prisma.company.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CompanyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CompanyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Company.
   * @param {CompanyUpsertArgs} args - Arguments to update or create a Company.
   * @example
   * // Update or create a Company
   * const company = await prisma.company.upsert({
   *   create: {
   *     // ... data to create a Company
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Company we want to update
   *   }
   * })
   */
  upsert<T extends CompanyUpsertArgs>(args: Prisma.SelectSubset<T, CompanyUpsertArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Companies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyCountArgs} args - Arguments to filter Companies to count.
   * @example
   * // Count the number of Companies
   * const count = await prisma.company.count({
   *   where: {
   *     // ... the filter for the Companies we want to count
   *   }
   * })
  **/
  count<T extends CompanyCountArgs>(
    args?: Prisma.Subset<T, CompanyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CompanyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Company.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CompanyAggregateArgs>(args: Prisma.Subset<T, CompanyAggregateArgs>): Prisma.PrismaPromise<GetCompanyAggregateType<T>>

  /**
   * Group by Company.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CompanyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CompanyGroupByArgs['orderBy'] }
      : { orderBy?: CompanyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CompanyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCompanyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Company model
 */
readonly fields: CompanyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Company.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CompanyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Nkp<T extends Prisma.Company$NkpArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$NkpArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NkpPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ApprovalSetting<T extends Prisma.Company$ApprovalSettingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$ApprovalSettingArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalSettingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Opportunity<T extends Prisma.Company$OpportunityArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$OpportunityArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OpportunityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Lead<T extends Prisma.Company$LeadArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$LeadArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Company model
 */
export interface CompanyFieldRefs {
  readonly id: Prisma.FieldRef<"Company", 'Int'>
  readonly code: Prisma.FieldRef<"Company", 'String'>
  readonly name: Prisma.FieldRef<"Company", 'String'>
  readonly isDefault: Prisma.FieldRef<"Company", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Company findUnique
 */
export type CompanyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company findUniqueOrThrow
 */
export type CompanyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company findFirst
 */
export type CompanyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Companies.
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Companies.
   */
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * Company findFirstOrThrow
 */
export type CompanyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Companies.
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Companies.
   */
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * Company findMany
 */
export type CompanyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Companies to fetch.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Companies.
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Companies.
   */
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * Company create
 */
export type CompanyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * The data needed to create a Company.
   */
  data: Prisma.XOR<Prisma.CompanyCreateInput, Prisma.CompanyUncheckedCreateInput>
}

/**
 * Company createMany
 */
export type CompanyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Companies.
   */
  data: Prisma.CompanyCreateManyInput | Prisma.CompanyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Company createManyAndReturn
 */
export type CompanyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * The data used to create many Companies.
   */
  data: Prisma.CompanyCreateManyInput | Prisma.CompanyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Company update
 */
export type CompanyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * The data needed to update a Company.
   */
  data: Prisma.XOR<Prisma.CompanyUpdateInput, Prisma.CompanyUncheckedUpdateInput>
  /**
   * Choose, which Company to update.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company updateMany
 */
export type CompanyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Companies.
   */
  data: Prisma.XOR<Prisma.CompanyUpdateManyMutationInput, Prisma.CompanyUncheckedUpdateManyInput>
  /**
   * Filter which Companies to update
   */
  where?: Prisma.CompanyWhereInput
  /**
   * Limit how many Companies to update.
   */
  limit?: number
}

/**
 * Company updateManyAndReturn
 */
export type CompanyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * The data used to update Companies.
   */
  data: Prisma.XOR<Prisma.CompanyUpdateManyMutationInput, Prisma.CompanyUncheckedUpdateManyInput>
  /**
   * Filter which Companies to update
   */
  where?: Prisma.CompanyWhereInput
  /**
   * Limit how many Companies to update.
   */
  limit?: number
}

/**
 * Company upsert
 */
export type CompanyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * The filter to search for the Company to update in case it exists.
   */
  where: Prisma.CompanyWhereUniqueInput
  /**
   * In case the Company found by the `where` argument doesn't exist, create a new Company with this data.
   */
  create: Prisma.XOR<Prisma.CompanyCreateInput, Prisma.CompanyUncheckedCreateInput>
  /**
   * In case the Company was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CompanyUpdateInput, Prisma.CompanyUncheckedUpdateInput>
}

/**
 * Company delete
 */
export type CompanyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter which Company to delete.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company deleteMany
 */
export type CompanyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Companies to delete
   */
  where?: Prisma.CompanyWhereInput
  /**
   * Limit how many Companies to delete.
   */
  limit?: number
}

/**
 * Company.Nkp
 */
export type Company$NkpArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nkp
   */
  select?: Prisma.NkpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nkp
   */
  omit?: Prisma.NkpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NkpInclude<ExtArgs> | null
  where?: Prisma.NkpWhereInput
  orderBy?: Prisma.NkpOrderByWithRelationInput | Prisma.NkpOrderByWithRelationInput[]
  cursor?: Prisma.NkpWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NkpScalarFieldEnum | Prisma.NkpScalarFieldEnum[]
}

/**
 * Company.ApprovalSetting
 */
export type Company$ApprovalSettingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalSetting
   */
  select?: Prisma.ApprovalSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalSetting
   */
  omit?: Prisma.ApprovalSettingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalSettingInclude<ExtArgs> | null
  where?: Prisma.ApprovalSettingWhereInput
  orderBy?: Prisma.ApprovalSettingOrderByWithRelationInput | Prisma.ApprovalSettingOrderByWithRelationInput[]
  cursor?: Prisma.ApprovalSettingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ApprovalSettingScalarFieldEnum | Prisma.ApprovalSettingScalarFieldEnum[]
}

/**
 * Company.Opportunity
 */
export type Company$OpportunityArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Opportunity
   */
  select?: Prisma.OpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Opportunity
   */
  omit?: Prisma.OpportunityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpportunityInclude<ExtArgs> | null
  where?: Prisma.OpportunityWhereInput
  orderBy?: Prisma.OpportunityOrderByWithRelationInput | Prisma.OpportunityOrderByWithRelationInput[]
  cursor?: Prisma.OpportunityWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OpportunityScalarFieldEnum | Prisma.OpportunityScalarFieldEnum[]
}

/**
 * Company.Lead
 */
export type Company$LeadArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  where?: Prisma.LeadWhereInput
  orderBy?: Prisma.LeadOrderByWithRelationInput | Prisma.LeadOrderByWithRelationInput[]
  cursor?: Prisma.LeadWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LeadScalarFieldEnum | Prisma.LeadScalarFieldEnum[]
}

/**
 * Company without action
 */
export type CompanyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
}
