
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Invoice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Invoice
 * 
 */
export type InvoiceModel = runtime.Types.Result.DefaultSelection<Prisma.$InvoicePayload>

export type AggregateInvoice = {
  _count: InvoiceCountAggregateOutputType | null
  _avg: InvoiceAvgAggregateOutputType | null
  _sum: InvoiceSumAggregateOutputType | null
  _min: InvoiceMinAggregateOutputType | null
  _max: InvoiceMaxAggregateOutputType | null
}

export type InvoiceAvgAggregateOutputType = {
  id: number | null
  totalAmount: number | null
  vatAmount: number | null
  grandTotal: number | null
  userId: number | null
  orderId: number | null
  customerId: number | null
}

export type InvoiceSumAggregateOutputType = {
  id: number | null
  totalAmount: number | null
  vatAmount: number | null
  grandTotal: number | null
  userId: number | null
  orderId: number | null
  customerId: number | null
}

export type InvoiceMinAggregateOutputType = {
  id: number | null
  number: string | null
  date: Date | null
  dueDate: Date | null
  status: $Enums.InvoiceStatus | null
  totalAmount: number | null
  vatAmount: number | null
  grandTotal: number | null
  userId: number | null
  orderId: number | null
  customerId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InvoiceMaxAggregateOutputType = {
  id: number | null
  number: string | null
  date: Date | null
  dueDate: Date | null
  status: $Enums.InvoiceStatus | null
  totalAmount: number | null
  vatAmount: number | null
  grandTotal: number | null
  userId: number | null
  orderId: number | null
  customerId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InvoiceCountAggregateOutputType = {
  id: number
  number: number
  date: number
  dueDate: number
  status: number
  attachments: number
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  customerId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type InvoiceAvgAggregateInputType = {
  id?: true
  totalAmount?: true
  vatAmount?: true
  grandTotal?: true
  userId?: true
  orderId?: true
  customerId?: true
}

export type InvoiceSumAggregateInputType = {
  id?: true
  totalAmount?: true
  vatAmount?: true
  grandTotal?: true
  userId?: true
  orderId?: true
  customerId?: true
}

export type InvoiceMinAggregateInputType = {
  id?: true
  number?: true
  date?: true
  dueDate?: true
  status?: true
  totalAmount?: true
  vatAmount?: true
  grandTotal?: true
  userId?: true
  orderId?: true
  customerId?: true
  createdAt?: true
  updatedAt?: true
}

export type InvoiceMaxAggregateInputType = {
  id?: true
  number?: true
  date?: true
  dueDate?: true
  status?: true
  totalAmount?: true
  vatAmount?: true
  grandTotal?: true
  userId?: true
  orderId?: true
  customerId?: true
  createdAt?: true
  updatedAt?: true
}

export type InvoiceCountAggregateInputType = {
  id?: true
  number?: true
  date?: true
  dueDate?: true
  status?: true
  attachments?: true
  totalAmount?: true
  vatAmount?: true
  grandTotal?: true
  userId?: true
  orderId?: true
  customerId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type InvoiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoice to aggregate.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Invoices
  **/
  _count?: true | InvoiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InvoiceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InvoiceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InvoiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InvoiceMaxAggregateInputType
}

export type GetInvoiceAggregateType<T extends InvoiceAggregateArgs> = {
      [P in keyof T & keyof AggregateInvoice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInvoice[P]>
    : Prisma.GetScalarType<T[P], AggregateInvoice[P]>
}




export type InvoiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceWhereInput
  orderBy?: Prisma.InvoiceOrderByWithAggregationInput | Prisma.InvoiceOrderByWithAggregationInput[]
  by: Prisma.InvoiceScalarFieldEnum[] | Prisma.InvoiceScalarFieldEnum
  having?: Prisma.InvoiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InvoiceCountAggregateInputType | true
  _avg?: InvoiceAvgAggregateInputType
  _sum?: InvoiceSumAggregateInputType
  _min?: InvoiceMinAggregateInputType
  _max?: InvoiceMaxAggregateInputType
}

export type InvoiceGroupByOutputType = {
  id: number
  number: string
  date: Date
  dueDate: Date
  status: $Enums.InvoiceStatus
  attachments: runtime.JsonValue | null
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  customerId: number
  createdAt: Date
  updatedAt: Date
  _count: InvoiceCountAggregateOutputType | null
  _avg: InvoiceAvgAggregateOutputType | null
  _sum: InvoiceSumAggregateOutputType | null
  _min: InvoiceMinAggregateOutputType | null
  _max: InvoiceMaxAggregateOutputType | null
}

export type GetInvoiceGroupByPayload<T extends InvoiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InvoiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InvoiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InvoiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InvoiceGroupByOutputType[P]>
      }
    >
  >



export type InvoiceWhereInput = {
  AND?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  OR?: Prisma.InvoiceWhereInput[]
  NOT?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  id?: Prisma.IntFilter<"Invoice"> | number
  number?: Prisma.StringFilter<"Invoice"> | string
  date?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  dueDate?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  status?: Prisma.EnumInvoiceStatusFilter<"Invoice"> | $Enums.InvoiceStatus
  attachments?: Prisma.JsonNullableFilter<"Invoice">
  totalAmount?: Prisma.FloatFilter<"Invoice"> | number
  vatAmount?: Prisma.FloatFilter<"Invoice"> | number
  grandTotal?: Prisma.FloatFilter<"Invoice"> | number
  userId?: Prisma.IntFilter<"Invoice"> | number
  orderId?: Prisma.IntFilter<"Invoice"> | number
  customerId?: Prisma.IntFilter<"Invoice"> | number
  createdAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  Customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
  Payments?: Prisma.PaymentListRelationFilter
  Order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  InvoiceItems?: Prisma.InvoiceItemListRelationFilter
}

export type InvoiceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachments?: Prisma.SortOrderInput | Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  Customer?: Prisma.CustomerOrderByWithRelationInput
  Payments?: Prisma.PaymentOrderByRelationAggregateInput
  Order?: Prisma.OrderOrderByWithRelationInput
  User?: Prisma.UserOrderByWithRelationInput
  InvoiceItems?: Prisma.InvoiceItemOrderByRelationAggregateInput
}

export type InvoiceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  number?: string
  orderId?: number
  AND?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  OR?: Prisma.InvoiceWhereInput[]
  NOT?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  date?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  dueDate?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  status?: Prisma.EnumInvoiceStatusFilter<"Invoice"> | $Enums.InvoiceStatus
  attachments?: Prisma.JsonNullableFilter<"Invoice">
  totalAmount?: Prisma.FloatFilter<"Invoice"> | number
  vatAmount?: Prisma.FloatFilter<"Invoice"> | number
  grandTotal?: Prisma.FloatFilter<"Invoice"> | number
  userId?: Prisma.IntFilter<"Invoice"> | number
  customerId?: Prisma.IntFilter<"Invoice"> | number
  createdAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  Customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
  Payments?: Prisma.PaymentListRelationFilter
  Order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  InvoiceItems?: Prisma.InvoiceItemListRelationFilter
}, "id" | "number" | "orderId">

export type InvoiceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachments?: Prisma.SortOrderInput | Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.InvoiceCountOrderByAggregateInput
  _avg?: Prisma.InvoiceAvgOrderByAggregateInput
  _max?: Prisma.InvoiceMaxOrderByAggregateInput
  _min?: Prisma.InvoiceMinOrderByAggregateInput
  _sum?: Prisma.InvoiceSumOrderByAggregateInput
}

export type InvoiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.InvoiceScalarWhereWithAggregatesInput | Prisma.InvoiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.InvoiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InvoiceScalarWhereWithAggregatesInput | Prisma.InvoiceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Invoice"> | number
  number?: Prisma.StringWithAggregatesFilter<"Invoice"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  dueDate?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  status?: Prisma.EnumInvoiceStatusWithAggregatesFilter<"Invoice"> | $Enums.InvoiceStatus
  attachments?: Prisma.JsonNullableWithAggregatesFilter<"Invoice">
  totalAmount?: Prisma.FloatWithAggregatesFilter<"Invoice"> | number
  vatAmount?: Prisma.FloatWithAggregatesFilter<"Invoice"> | number
  grandTotal?: Prisma.FloatWithAggregatesFilter<"Invoice"> | number
  userId?: Prisma.IntWithAggregatesFilter<"Invoice"> | number
  orderId?: Prisma.IntWithAggregatesFilter<"Invoice"> | number
  customerId?: Prisma.IntWithAggregatesFilter<"Invoice"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Invoice"> | Date | string
}

export type InvoiceCreateInput = {
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Customer: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
  Payments?: Prisma.PaymentCreateNestedManyWithoutInvoiceInput
  Order: Prisma.OrderCreateNestedOneWithoutInvoiceInput
  User: Prisma.UserCreateNestedOneWithoutInvoicesInput
  InvoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUncheckedCreateInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutInvoiceInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUpdateInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Customer?: Prisma.CustomerUpdateOneRequiredWithoutInvoicesNestedInput
  Payments?: Prisma.PaymentUpdateManyWithoutInvoiceNestedInput
  Order?: Prisma.OrderUpdateOneRequiredWithoutInvoiceNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutInvoicesNestedInput
  InvoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Payments?: Prisma.PaymentUncheckedUpdateManyWithoutInvoiceNestedInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceCreateManyInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InvoiceUpdateManyMutationInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InvoiceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InvoiceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attachments?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InvoiceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InvoiceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InvoiceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  grandTotal?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceScalarRelationFilter = {
  is?: Prisma.InvoiceWhereInput
  isNot?: Prisma.InvoiceWhereInput
}

export type InvoiceListRelationFilter = {
  every?: Prisma.InvoiceWhereInput
  some?: Prisma.InvoiceWhereInput
  none?: Prisma.InvoiceWhereInput
}

export type InvoiceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InvoiceNullableScalarRelationFilter = {
  is?: Prisma.InvoiceWhereInput | null
  isNot?: Prisma.InvoiceWhereInput | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type EnumInvoiceStatusFieldUpdateOperationsInput = {
  set?: $Enums.InvoiceStatus
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type InvoiceCreateNestedOneWithoutInvoiceItemsInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutInvoiceItemsInput
  connect?: Prisma.InvoiceWhereUniqueInput
}

export type InvoiceUpdateOneRequiredWithoutInvoiceItemsNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutInvoiceItemsInput
  upsert?: Prisma.InvoiceUpsertWithoutInvoiceItemsInput
  connect?: Prisma.InvoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoiceUpdateToOneWithWhereWithoutInvoiceItemsInput, Prisma.InvoiceUpdateWithoutInvoiceItemsInput>, Prisma.InvoiceUncheckedUpdateWithoutInvoiceItemsInput>
}

export type InvoiceCreateNestedOneWithoutPaymentsInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutPaymentsInput, Prisma.InvoiceUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutPaymentsInput
  connect?: Prisma.InvoiceWhereUniqueInput
}

export type InvoiceUpdateOneRequiredWithoutPaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutPaymentsInput, Prisma.InvoiceUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutPaymentsInput
  upsert?: Prisma.InvoiceUpsertWithoutPaymentsInput
  connect?: Prisma.InvoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoiceUpdateToOneWithWhereWithoutPaymentsInput, Prisma.InvoiceUpdateWithoutPaymentsInput>, Prisma.InvoiceUncheckedUpdateWithoutPaymentsInput>
}

export type InvoiceCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput | Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput | Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceCreateNestedOneWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutOrderInput, Prisma.InvoiceUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutOrderInput
  connect?: Prisma.InvoiceWhereUniqueInput
}

export type InvoiceUncheckedCreateNestedOneWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutOrderInput, Prisma.InvoiceUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutOrderInput
  connect?: Prisma.InvoiceWhereUniqueInput
}

export type InvoiceUpdateOneWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutOrderInput, Prisma.InvoiceUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutOrderInput
  upsert?: Prisma.InvoiceUpsertWithoutOrderInput
  disconnect?: Prisma.InvoiceWhereInput | boolean
  delete?: Prisma.InvoiceWhereInput | boolean
  connect?: Prisma.InvoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoiceUpdateToOneWithWhereWithoutOrderInput, Prisma.InvoiceUpdateWithoutOrderInput>, Prisma.InvoiceUncheckedUpdateWithoutOrderInput>
}

export type InvoiceUncheckedUpdateOneWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutOrderInput, Prisma.InvoiceUncheckedCreateWithoutOrderInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutOrderInput
  upsert?: Prisma.InvoiceUpsertWithoutOrderInput
  disconnect?: Prisma.InvoiceWhereInput | boolean
  delete?: Prisma.InvoiceWhereInput | boolean
  connect?: Prisma.InvoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoiceUpdateToOneWithWhereWithoutOrderInput, Prisma.InvoiceUpdateWithoutOrderInput>, Prisma.InvoiceUncheckedUpdateWithoutOrderInput>
}

export type InvoiceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutUserInput | Prisma.InvoiceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput> | Prisma.InvoiceCreateWithoutUserInput[] | Prisma.InvoiceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutUserInput | Prisma.InvoiceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InvoiceCreateManyUserInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutUserInput | Prisma.InvoiceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceCreateWithoutInvoiceItemsInput = {
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Customer: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
  Payments?: Prisma.PaymentCreateNestedManyWithoutInvoiceInput
  Order: Prisma.OrderCreateNestedOneWithoutInvoiceInput
  User: Prisma.UserCreateNestedOneWithoutInvoicesInput
}

export type InvoiceUncheckedCreateWithoutInvoiceItemsInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceCreateOrConnectWithoutInvoiceItemsInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
}

export type InvoiceUpsertWithoutInvoiceItemsInput = {
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedUpdateWithoutInvoiceItemsInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
  where?: Prisma.InvoiceWhereInput
}

export type InvoiceUpdateToOneWithWhereWithoutInvoiceItemsInput = {
  where?: Prisma.InvoiceWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedUpdateWithoutInvoiceItemsInput>
}

export type InvoiceUpdateWithoutInvoiceItemsInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Customer?: Prisma.CustomerUpdateOneRequiredWithoutInvoicesNestedInput
  Payments?: Prisma.PaymentUpdateManyWithoutInvoiceNestedInput
  Order?: Prisma.OrderUpdateOneRequiredWithoutInvoiceNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutInvoicesNestedInput
}

export type InvoiceUncheckedUpdateWithoutInvoiceItemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Payments?: Prisma.PaymentUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceCreateWithoutPaymentsInput = {
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Customer: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
  Order: Prisma.OrderCreateNestedOneWithoutInvoiceInput
  User: Prisma.UserCreateNestedOneWithoutInvoicesInput
  InvoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUncheckedCreateWithoutPaymentsInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  InvoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceCreateOrConnectWithoutPaymentsInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutPaymentsInput, Prisma.InvoiceUncheckedCreateWithoutPaymentsInput>
}

export type InvoiceUpsertWithoutPaymentsInput = {
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutPaymentsInput, Prisma.InvoiceUncheckedUpdateWithoutPaymentsInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutPaymentsInput, Prisma.InvoiceUncheckedCreateWithoutPaymentsInput>
  where?: Prisma.InvoiceWhereInput
}

export type InvoiceUpdateToOneWithWhereWithoutPaymentsInput = {
  where?: Prisma.InvoiceWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutPaymentsInput, Prisma.InvoiceUncheckedUpdateWithoutPaymentsInput>
}

export type InvoiceUpdateWithoutPaymentsInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Customer?: Prisma.CustomerUpdateOneRequiredWithoutInvoicesNestedInput
  Order?: Prisma.OrderUpdateOneRequiredWithoutInvoiceNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutInvoicesNestedInput
  InvoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateWithoutPaymentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  InvoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceCreateWithoutCustomerInput = {
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Payments?: Prisma.PaymentCreateNestedManyWithoutInvoiceInput
  Order: Prisma.OrderCreateNestedOneWithoutInvoiceInput
  User: Prisma.UserCreateNestedOneWithoutInvoicesInput
  InvoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUncheckedCreateWithoutCustomerInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutInvoiceInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceCreateOrConnectWithoutCustomerInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput>
}

export type InvoiceCreateManyCustomerInputEnvelope = {
  data: Prisma.InvoiceCreateManyCustomerInput | Prisma.InvoiceCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type InvoiceUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.InvoiceWhereUniqueInput
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutCustomerInput, Prisma.InvoiceUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput>
}

export type InvoiceUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.InvoiceWhereUniqueInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutCustomerInput, Prisma.InvoiceUncheckedUpdateWithoutCustomerInput>
}

export type InvoiceUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.InvoiceScalarWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyWithoutCustomerInput>
}

export type InvoiceScalarWhereInput = {
  AND?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
  OR?: Prisma.InvoiceScalarWhereInput[]
  NOT?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
  id?: Prisma.IntFilter<"Invoice"> | number
  number?: Prisma.StringFilter<"Invoice"> | string
  date?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  dueDate?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  status?: Prisma.EnumInvoiceStatusFilter<"Invoice"> | $Enums.InvoiceStatus
  attachments?: Prisma.JsonNullableFilter<"Invoice">
  totalAmount?: Prisma.FloatFilter<"Invoice"> | number
  vatAmount?: Prisma.FloatFilter<"Invoice"> | number
  grandTotal?: Prisma.FloatFilter<"Invoice"> | number
  userId?: Prisma.IntFilter<"Invoice"> | number
  orderId?: Prisma.IntFilter<"Invoice"> | number
  customerId?: Prisma.IntFilter<"Invoice"> | number
  createdAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Invoice"> | Date | string
}

export type InvoiceCreateWithoutOrderInput = {
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Customer: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
  Payments?: Prisma.PaymentCreateNestedManyWithoutInvoiceInput
  User: Prisma.UserCreateNestedOneWithoutInvoicesInput
  InvoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUncheckedCreateWithoutOrderInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutInvoiceInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceCreateOrConnectWithoutOrderInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutOrderInput, Prisma.InvoiceUncheckedCreateWithoutOrderInput>
}

export type InvoiceUpsertWithoutOrderInput = {
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutOrderInput, Prisma.InvoiceUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutOrderInput, Prisma.InvoiceUncheckedCreateWithoutOrderInput>
  where?: Prisma.InvoiceWhereInput
}

export type InvoiceUpdateToOneWithWhereWithoutOrderInput = {
  where?: Prisma.InvoiceWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutOrderInput, Prisma.InvoiceUncheckedUpdateWithoutOrderInput>
}

export type InvoiceUpdateWithoutOrderInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Customer?: Prisma.CustomerUpdateOneRequiredWithoutInvoicesNestedInput
  Payments?: Prisma.PaymentUpdateManyWithoutInvoiceNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutInvoicesNestedInput
  InvoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Payments?: Prisma.PaymentUncheckedUpdateManyWithoutInvoiceNestedInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceCreateWithoutUserInput = {
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Customer: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
  Payments?: Prisma.PaymentCreateNestedManyWithoutInvoiceInput
  Order: Prisma.OrderCreateNestedOneWithoutInvoiceInput
  InvoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUncheckedCreateWithoutUserInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  orderId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  Payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutInvoiceInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceCreateOrConnectWithoutUserInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput>
}

export type InvoiceCreateManyUserInputEnvelope = {
  data: Prisma.InvoiceCreateManyUserInput | Prisma.InvoiceCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type InvoiceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.InvoiceWhereUniqueInput
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutUserInput, Prisma.InvoiceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutUserInput, Prisma.InvoiceUncheckedCreateWithoutUserInput>
}

export type InvoiceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.InvoiceWhereUniqueInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutUserInput, Prisma.InvoiceUncheckedUpdateWithoutUserInput>
}

export type InvoiceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.InvoiceScalarWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyWithoutUserInput>
}

export type InvoiceCreateManyCustomerInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  userId: number
  orderId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InvoiceUpdateWithoutCustomerInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Payments?: Prisma.PaymentUpdateManyWithoutInvoiceNestedInput
  Order?: Prisma.OrderUpdateOneRequiredWithoutInvoiceNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutInvoicesNestedInput
  InvoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Payments?: Prisma.PaymentUncheckedUpdateManyWithoutInvoiceNestedInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InvoiceCreateManyUserInput = {
  id?: number
  number: string
  date: Date | string
  dueDate: Date | string
  status: $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount: number
  vatAmount: number
  grandTotal: number
  orderId: number
  customerId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InvoiceUpdateWithoutUserInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Customer?: Prisma.CustomerUpdateOneRequiredWithoutInvoicesNestedInput
  Payments?: Prisma.PaymentUpdateManyWithoutInvoiceNestedInput
  Order?: Prisma.OrderUpdateOneRequiredWithoutInvoiceNestedInput
  InvoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Payments?: Prisma.PaymentUncheckedUpdateManyWithoutInvoiceNestedInput
  InvoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  attachments?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  grandTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type InvoiceCountOutputType
 */

export type InvoiceCountOutputType = {
  Payments: number
  InvoiceItems: number
}

export type InvoiceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Payments?: boolean | InvoiceCountOutputTypeCountPaymentsArgs
  InvoiceItems?: boolean | InvoiceCountOutputTypeCountInvoiceItemsArgs
}

/**
 * InvoiceCountOutputType without action
 */
export type InvoiceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceCountOutputType
   */
  select?: Prisma.InvoiceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * InvoiceCountOutputType without action
 */
export type InvoiceCountOutputTypeCountPaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentWhereInput
}

/**
 * InvoiceCountOutputType without action
 */
export type InvoiceCountOutputTypeCountInvoiceItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceItemWhereInput
}


export type InvoiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  number?: boolean
  date?: boolean
  dueDate?: boolean
  status?: boolean
  attachments?: boolean
  totalAmount?: boolean
  vatAmount?: boolean
  grandTotal?: boolean
  userId?: boolean
  orderId?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  Payments?: boolean | Prisma.Invoice$PaymentsArgs<ExtArgs>
  Order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  InvoiceItems?: boolean | Prisma.Invoice$InvoiceItemsArgs<ExtArgs>
  _count?: boolean | Prisma.InvoiceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>

export type InvoiceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  number?: boolean
  date?: boolean
  dueDate?: boolean
  status?: boolean
  attachments?: boolean
  totalAmount?: boolean
  vatAmount?: boolean
  grandTotal?: boolean
  userId?: boolean
  orderId?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  Order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>

export type InvoiceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  number?: boolean
  date?: boolean
  dueDate?: boolean
  status?: boolean
  attachments?: boolean
  totalAmount?: boolean
  vatAmount?: boolean
  grandTotal?: boolean
  userId?: boolean
  orderId?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  Order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>

export type InvoiceSelectScalar = {
  id?: boolean
  number?: boolean
  date?: boolean
  dueDate?: boolean
  status?: boolean
  attachments?: boolean
  totalAmount?: boolean
  vatAmount?: boolean
  grandTotal?: boolean
  userId?: boolean
  orderId?: boolean
  customerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type InvoiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "number" | "date" | "dueDate" | "status" | "attachments" | "totalAmount" | "vatAmount" | "grandTotal" | "userId" | "orderId" | "customerId" | "createdAt" | "updatedAt", ExtArgs["result"]["invoice"]>
export type InvoiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  Payments?: boolean | Prisma.Invoice$PaymentsArgs<ExtArgs>
  Order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  InvoiceItems?: boolean | Prisma.Invoice$InvoiceItemsArgs<ExtArgs>
  _count?: boolean | Prisma.InvoiceCountOutputTypeDefaultArgs<ExtArgs>
}
export type InvoiceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  Order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type InvoiceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
  Order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $InvoicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Invoice"
  objects: {
    Customer: Prisma.$CustomerPayload<ExtArgs>
    Payments: Prisma.$PaymentPayload<ExtArgs>[]
    Order: Prisma.$OrderPayload<ExtArgs>
    User: Prisma.$UserPayload<ExtArgs>
    InvoiceItems: Prisma.$InvoiceItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    number: string
    date: Date
    dueDate: Date
    status: $Enums.InvoiceStatus
    attachments: runtime.JsonValue | null
    totalAmount: number
    vatAmount: number
    grandTotal: number
    userId: number
    orderId: number
    customerId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["invoice"]>
  composites: {}
}

export type InvoiceGetPayload<S extends boolean | null | undefined | InvoiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InvoicePayload, S>

export type InvoiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InvoiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InvoiceCountAggregateInputType | true
  }

export interface InvoiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Invoice'], meta: { name: 'Invoice' } }
  /**
   * Find zero or one Invoice that matches the filter.
   * @param {InvoiceFindUniqueArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InvoiceFindUniqueArgs>(args: Prisma.SelectSubset<T, InvoiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Invoice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InvoiceFindUniqueOrThrowArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InvoiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InvoiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindFirstArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InvoiceFindFirstArgs>(args?: Prisma.SelectSubset<T, InvoiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindFirstOrThrowArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InvoiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InvoiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Invoices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Invoices
   * const invoices = await prisma.invoice.findMany()
   * 
   * // Get first 10 Invoices
   * const invoices = await prisma.invoice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const invoiceWithIdOnly = await prisma.invoice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InvoiceFindManyArgs>(args?: Prisma.SelectSubset<T, InvoiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Invoice.
   * @param {InvoiceCreateArgs} args - Arguments to create a Invoice.
   * @example
   * // Create one Invoice
   * const Invoice = await prisma.invoice.create({
   *   data: {
   *     // ... data to create a Invoice
   *   }
   * })
   * 
   */
  create<T extends InvoiceCreateArgs>(args: Prisma.SelectSubset<T, InvoiceCreateArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Invoices.
   * @param {InvoiceCreateManyArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoice = await prisma.invoice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InvoiceCreateManyArgs>(args?: Prisma.SelectSubset<T, InvoiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Invoices and returns the data saved in the database.
   * @param {InvoiceCreateManyAndReturnArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoice = await prisma.invoice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Invoices and only return the `id`
   * const invoiceWithIdOnly = await prisma.invoice.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InvoiceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InvoiceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Invoice.
   * @param {InvoiceDeleteArgs} args - Arguments to delete one Invoice.
   * @example
   * // Delete one Invoice
   * const Invoice = await prisma.invoice.delete({
   *   where: {
   *     // ... filter to delete one Invoice
   *   }
   * })
   * 
   */
  delete<T extends InvoiceDeleteArgs>(args: Prisma.SelectSubset<T, InvoiceDeleteArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Invoice.
   * @param {InvoiceUpdateArgs} args - Arguments to update one Invoice.
   * @example
   * // Update one Invoice
   * const invoice = await prisma.invoice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InvoiceUpdateArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Invoices.
   * @param {InvoiceDeleteManyArgs} args - Arguments to filter Invoices to delete.
   * @example
   * // Delete a few Invoices
   * const { count } = await prisma.invoice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InvoiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, InvoiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Invoices
   * const invoice = await prisma.invoice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InvoiceUpdateManyArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices and returns the data updated in the database.
   * @param {InvoiceUpdateManyAndReturnArgs} args - Arguments to update many Invoices.
   * @example
   * // Update many Invoices
   * const invoice = await prisma.invoice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Invoices and only return the `id`
   * const invoiceWithIdOnly = await prisma.invoice.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InvoiceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Invoice.
   * @param {InvoiceUpsertArgs} args - Arguments to update or create a Invoice.
   * @example
   * // Update or create a Invoice
   * const invoice = await prisma.invoice.upsert({
   *   create: {
   *     // ... data to create a Invoice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Invoice we want to update
   *   }
   * })
   */
  upsert<T extends InvoiceUpsertArgs>(args: Prisma.SelectSubset<T, InvoiceUpsertArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceCountArgs} args - Arguments to filter Invoices to count.
   * @example
   * // Count the number of Invoices
   * const count = await prisma.invoice.count({
   *   where: {
   *     // ... the filter for the Invoices we want to count
   *   }
   * })
  **/
  count<T extends InvoiceCountArgs>(
    args?: Prisma.Subset<T, InvoiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InvoiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Invoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InvoiceAggregateArgs>(args: Prisma.Subset<T, InvoiceAggregateArgs>): Prisma.PrismaPromise<GetInvoiceAggregateType<T>>

  /**
   * Group by Invoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InvoiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InvoiceGroupByArgs['orderBy'] }
      : { orderBy?: InvoiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InvoiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInvoiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Invoice model
 */
readonly fields: InvoiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Invoice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InvoiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Customer<T extends Prisma.CustomerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomerDefaultArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Payments<T extends Prisma.Invoice$PaymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoice$PaymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  InvoiceItems<T extends Prisma.Invoice$InvoiceItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoice$InvoiceItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Invoice model
 */
export interface InvoiceFieldRefs {
  readonly id: Prisma.FieldRef<"Invoice", 'Int'>
  readonly number: Prisma.FieldRef<"Invoice", 'String'>
  readonly date: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly dueDate: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly status: Prisma.FieldRef<"Invoice", 'InvoiceStatus'>
  readonly attachments: Prisma.FieldRef<"Invoice", 'Json'>
  readonly totalAmount: Prisma.FieldRef<"Invoice", 'Float'>
  readonly vatAmount: Prisma.FieldRef<"Invoice", 'Float'>
  readonly grandTotal: Prisma.FieldRef<"Invoice", 'Float'>
  readonly userId: Prisma.FieldRef<"Invoice", 'Int'>
  readonly orderId: Prisma.FieldRef<"Invoice", 'Int'>
  readonly customerId: Prisma.FieldRef<"Invoice", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Invoice", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Invoice findUnique
 */
export type InvoiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice findUniqueOrThrow
 */
export type InvoiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice findFirst
 */
export type InvoiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice findFirstOrThrow
 */
export type InvoiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice findMany
 */
export type InvoiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice create
 */
export type InvoiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The data needed to create a Invoice.
   */
  data: Prisma.XOR<Prisma.InvoiceCreateInput, Prisma.InvoiceUncheckedCreateInput>
}

/**
 * Invoice createMany
 */
export type InvoiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoiceCreateManyInput | Prisma.InvoiceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Invoice createManyAndReturn
 */
export type InvoiceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoiceCreateManyInput | Prisma.InvoiceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Invoice update
 */
export type InvoiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The data needed to update a Invoice.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateInput, Prisma.InvoiceUncheckedUpdateInput>
  /**
   * Choose, which Invoice to update.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice updateMany
 */
export type InvoiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
}

/**
 * Invoice updateManyAndReturn
 */
export type InvoiceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Invoice upsert
 */
export type InvoiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The filter to search for the Invoice to update in case it exists.
   */
  where: Prisma.InvoiceWhereUniqueInput
  /**
   * In case the Invoice found by the `where` argument doesn't exist, create a new Invoice with this data.
   */
  create: Prisma.XOR<Prisma.InvoiceCreateInput, Prisma.InvoiceUncheckedCreateInput>
  /**
   * In case the Invoice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InvoiceUpdateInput, Prisma.InvoiceUncheckedUpdateInput>
}

/**
 * Invoice delete
 */
export type InvoiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter which Invoice to delete.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice deleteMany
 */
export type InvoiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoices to delete
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to delete.
   */
  limit?: number
}

/**
 * Invoice.Payments
 */
export type Invoice$PaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Payment
   */
  select?: Prisma.PaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Payment
   */
  omit?: Prisma.PaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentInclude<ExtArgs> | null
  where?: Prisma.PaymentWhereInput
  orderBy?: Prisma.PaymentOrderByWithRelationInput | Prisma.PaymentOrderByWithRelationInput[]
  cursor?: Prisma.PaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentScalarFieldEnum | Prisma.PaymentScalarFieldEnum[]
}

/**
 * Invoice.InvoiceItems
 */
export type Invoice$InvoiceItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceItem
   */
  select?: Prisma.InvoiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceItem
   */
  omit?: Prisma.InvoiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceItemInclude<ExtArgs> | null
  where?: Prisma.InvoiceItemWhereInput
  orderBy?: Prisma.InvoiceItemOrderByWithRelationInput | Prisma.InvoiceItemOrderByWithRelationInput[]
  cursor?: Prisma.InvoiceItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvoiceItemScalarFieldEnum | Prisma.InvoiceItemScalarFieldEnum[]
}

/**
 * Invoice without action
 */
export type InvoiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
}
