
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JournalLine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model JournalLine
 * 
 */
export type JournalLineModel = runtime.Types.Result.DefaultSelection<Prisma.$JournalLinePayload>

export type AggregateJournalLine = {
  _count: JournalLineCountAggregateOutputType | null
  _avg: JournalLineAvgAggregateOutputType | null
  _sum: JournalLineSumAggregateOutputType | null
  _min: JournalLineMinAggregateOutputType | null
  _max: JournalLineMaxAggregateOutputType | null
}

export type JournalLineAvgAggregateOutputType = {
  id: number | null
  journalId: number | null
  accountId: number | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
  sortOrder: number | null
}

export type JournalLineSumAggregateOutputType = {
  id: number | null
  journalId: number | null
  accountId: number | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
  sortOrder: number | null
}

export type JournalLineMinAggregateOutputType = {
  id: number | null
  journalId: number | null
  accountId: number | null
  description: string | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
  sortOrder: number | null
}

export type JournalLineMaxAggregateOutputType = {
  id: number | null
  journalId: number | null
  accountId: number | null
  description: string | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
  sortOrder: number | null
}

export type JournalLineCountAggregateOutputType = {
  id: number
  journalId: number
  accountId: number
  description: number
  debit: number
  credit: number
  sortOrder: number
  _all: number
}


export type JournalLineAvgAggregateInputType = {
  id?: true
  journalId?: true
  accountId?: true
  debit?: true
  credit?: true
  sortOrder?: true
}

export type JournalLineSumAggregateInputType = {
  id?: true
  journalId?: true
  accountId?: true
  debit?: true
  credit?: true
  sortOrder?: true
}

export type JournalLineMinAggregateInputType = {
  id?: true
  journalId?: true
  accountId?: true
  description?: true
  debit?: true
  credit?: true
  sortOrder?: true
}

export type JournalLineMaxAggregateInputType = {
  id?: true
  journalId?: true
  accountId?: true
  description?: true
  debit?: true
  credit?: true
  sortOrder?: true
}

export type JournalLineCountAggregateInputType = {
  id?: true
  journalId?: true
  accountId?: true
  description?: true
  debit?: true
  credit?: true
  sortOrder?: true
  _all?: true
}

export type JournalLineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JournalLine to aggregate.
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalLines to fetch.
   */
  orderBy?: Prisma.JournalLineOrderByWithRelationInput | Prisma.JournalLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JournalLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JournalLines
  **/
  _count?: true | JournalLineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: JournalLineAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: JournalLineSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JournalLineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JournalLineMaxAggregateInputType
}

export type GetJournalLineAggregateType<T extends JournalLineAggregateArgs> = {
      [P in keyof T & keyof AggregateJournalLine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJournalLine[P]>
    : Prisma.GetScalarType<T[P], AggregateJournalLine[P]>
}




export type JournalLineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JournalLineWhereInput
  orderBy?: Prisma.JournalLineOrderByWithAggregationInput | Prisma.JournalLineOrderByWithAggregationInput[]
  by: Prisma.JournalLineScalarFieldEnum[] | Prisma.JournalLineScalarFieldEnum
  having?: Prisma.JournalLineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JournalLineCountAggregateInputType | true
  _avg?: JournalLineAvgAggregateInputType
  _sum?: JournalLineSumAggregateInputType
  _min?: JournalLineMinAggregateInputType
  _max?: JournalLineMaxAggregateInputType
}

export type JournalLineGroupByOutputType = {
  id: number
  journalId: number
  accountId: number
  description: string | null
  debit: runtime.Decimal
  credit: runtime.Decimal
  sortOrder: number
  _count: JournalLineCountAggregateOutputType | null
  _avg: JournalLineAvgAggregateOutputType | null
  _sum: JournalLineSumAggregateOutputType | null
  _min: JournalLineMinAggregateOutputType | null
  _max: JournalLineMaxAggregateOutputType | null
}

export type GetJournalLineGroupByPayload<T extends JournalLineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JournalLineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JournalLineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JournalLineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JournalLineGroupByOutputType[P]>
      }
    >
  >



export type JournalLineWhereInput = {
  AND?: Prisma.JournalLineWhereInput | Prisma.JournalLineWhereInput[]
  OR?: Prisma.JournalLineWhereInput[]
  NOT?: Prisma.JournalLineWhereInput | Prisma.JournalLineWhereInput[]
  id?: Prisma.IntFilter<"JournalLine"> | number
  journalId?: Prisma.IntFilter<"JournalLine"> | number
  accountId?: Prisma.IntFilter<"JournalLine"> | number
  description?: Prisma.StringNullableFilter<"JournalLine"> | string | null
  debit?: Prisma.DecimalFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFilter<"JournalLine"> | number
  journal?: Prisma.XOR<Prisma.JournalEntryScalarRelationFilter, Prisma.JournalEntryWhereInput>
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
}

export type JournalLineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  journal?: Prisma.JournalEntryOrderByWithRelationInput
  account?: Prisma.AccountOrderByWithRelationInput
}

export type JournalLineWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.JournalLineWhereInput | Prisma.JournalLineWhereInput[]
  OR?: Prisma.JournalLineWhereInput[]
  NOT?: Prisma.JournalLineWhereInput | Prisma.JournalLineWhereInput[]
  journalId?: Prisma.IntFilter<"JournalLine"> | number
  accountId?: Prisma.IntFilter<"JournalLine"> | number
  description?: Prisma.StringNullableFilter<"JournalLine"> | string | null
  debit?: Prisma.DecimalFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFilter<"JournalLine"> | number
  journal?: Prisma.XOR<Prisma.JournalEntryScalarRelationFilter, Prisma.JournalEntryWhereInput>
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
}, "id">

export type JournalLineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  _count?: Prisma.JournalLineCountOrderByAggregateInput
  _avg?: Prisma.JournalLineAvgOrderByAggregateInput
  _max?: Prisma.JournalLineMaxOrderByAggregateInput
  _min?: Prisma.JournalLineMinOrderByAggregateInput
  _sum?: Prisma.JournalLineSumOrderByAggregateInput
}

export type JournalLineScalarWhereWithAggregatesInput = {
  AND?: Prisma.JournalLineScalarWhereWithAggregatesInput | Prisma.JournalLineScalarWhereWithAggregatesInput[]
  OR?: Prisma.JournalLineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JournalLineScalarWhereWithAggregatesInput | Prisma.JournalLineScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"JournalLine"> | number
  journalId?: Prisma.IntWithAggregatesFilter<"JournalLine"> | number
  accountId?: Prisma.IntWithAggregatesFilter<"JournalLine"> | number
  description?: Prisma.StringNullableWithAggregatesFilter<"JournalLine"> | string | null
  debit?: Prisma.DecimalWithAggregatesFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalWithAggregatesFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntWithAggregatesFilter<"JournalLine"> | number
}

export type JournalLineCreateInput = {
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
  journal: Prisma.JournalEntryCreateNestedOneWithoutLinesInput
  account: Prisma.AccountCreateNestedOneWithoutJournalLinesInput
}

export type JournalLineUncheckedCreateInput = {
  id?: number
  journalId: number
  accountId: number
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
}

export type JournalLineUpdateInput = {
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  journal?: Prisma.JournalEntryUpdateOneRequiredWithoutLinesNestedInput
  account?: Prisma.AccountUpdateOneRequiredWithoutJournalLinesNestedInput
}

export type JournalLineUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journalId?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type JournalLineCreateManyInput = {
  id?: number
  journalId: number
  accountId: number
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
}

export type JournalLineUpdateManyMutationInput = {
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type JournalLineUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journalId?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type JournalLineListRelationFilter = {
  every?: Prisma.JournalLineWhereInput
  some?: Prisma.JournalLineWhereInput
  none?: Prisma.JournalLineWhereInput
}

export type JournalLineOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type JournalLineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type JournalLineAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type JournalLineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type JournalLineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type JournalLineSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journalId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type JournalLineCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutAccountInput, Prisma.JournalLineUncheckedCreateWithoutAccountInput> | Prisma.JournalLineCreateWithoutAccountInput[] | Prisma.JournalLineUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutAccountInput | Prisma.JournalLineCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.JournalLineCreateManyAccountInputEnvelope
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
}

export type JournalLineUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutAccountInput, Prisma.JournalLineUncheckedCreateWithoutAccountInput> | Prisma.JournalLineCreateWithoutAccountInput[] | Prisma.JournalLineUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutAccountInput | Prisma.JournalLineCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.JournalLineCreateManyAccountInputEnvelope
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
}

export type JournalLineUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutAccountInput, Prisma.JournalLineUncheckedCreateWithoutAccountInput> | Prisma.JournalLineCreateWithoutAccountInput[] | Prisma.JournalLineUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutAccountInput | Prisma.JournalLineCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.JournalLineUpsertWithWhereUniqueWithoutAccountInput | Prisma.JournalLineUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.JournalLineCreateManyAccountInputEnvelope
  set?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  disconnect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  delete?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  update?: Prisma.JournalLineUpdateWithWhereUniqueWithoutAccountInput | Prisma.JournalLineUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.JournalLineUpdateManyWithWhereWithoutAccountInput | Prisma.JournalLineUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.JournalLineScalarWhereInput | Prisma.JournalLineScalarWhereInput[]
}

export type JournalLineUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutAccountInput, Prisma.JournalLineUncheckedCreateWithoutAccountInput> | Prisma.JournalLineCreateWithoutAccountInput[] | Prisma.JournalLineUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutAccountInput | Prisma.JournalLineCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.JournalLineUpsertWithWhereUniqueWithoutAccountInput | Prisma.JournalLineUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.JournalLineCreateManyAccountInputEnvelope
  set?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  disconnect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  delete?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  update?: Prisma.JournalLineUpdateWithWhereUniqueWithoutAccountInput | Prisma.JournalLineUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.JournalLineUpdateManyWithWhereWithoutAccountInput | Prisma.JournalLineUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.JournalLineScalarWhereInput | Prisma.JournalLineScalarWhereInput[]
}

export type JournalLineCreateNestedManyWithoutJournalInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutJournalInput, Prisma.JournalLineUncheckedCreateWithoutJournalInput> | Prisma.JournalLineCreateWithoutJournalInput[] | Prisma.JournalLineUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutJournalInput | Prisma.JournalLineCreateOrConnectWithoutJournalInput[]
  createMany?: Prisma.JournalLineCreateManyJournalInputEnvelope
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
}

export type JournalLineUncheckedCreateNestedManyWithoutJournalInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutJournalInput, Prisma.JournalLineUncheckedCreateWithoutJournalInput> | Prisma.JournalLineCreateWithoutJournalInput[] | Prisma.JournalLineUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutJournalInput | Prisma.JournalLineCreateOrConnectWithoutJournalInput[]
  createMany?: Prisma.JournalLineCreateManyJournalInputEnvelope
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
}

export type JournalLineUpdateManyWithoutJournalNestedInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutJournalInput, Prisma.JournalLineUncheckedCreateWithoutJournalInput> | Prisma.JournalLineCreateWithoutJournalInput[] | Prisma.JournalLineUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutJournalInput | Prisma.JournalLineCreateOrConnectWithoutJournalInput[]
  upsert?: Prisma.JournalLineUpsertWithWhereUniqueWithoutJournalInput | Prisma.JournalLineUpsertWithWhereUniqueWithoutJournalInput[]
  createMany?: Prisma.JournalLineCreateManyJournalInputEnvelope
  set?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  disconnect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  delete?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  update?: Prisma.JournalLineUpdateWithWhereUniqueWithoutJournalInput | Prisma.JournalLineUpdateWithWhereUniqueWithoutJournalInput[]
  updateMany?: Prisma.JournalLineUpdateManyWithWhereWithoutJournalInput | Prisma.JournalLineUpdateManyWithWhereWithoutJournalInput[]
  deleteMany?: Prisma.JournalLineScalarWhereInput | Prisma.JournalLineScalarWhereInput[]
}

export type JournalLineUncheckedUpdateManyWithoutJournalNestedInput = {
  create?: Prisma.XOR<Prisma.JournalLineCreateWithoutJournalInput, Prisma.JournalLineUncheckedCreateWithoutJournalInput> | Prisma.JournalLineCreateWithoutJournalInput[] | Prisma.JournalLineUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalLineCreateOrConnectWithoutJournalInput | Prisma.JournalLineCreateOrConnectWithoutJournalInput[]
  upsert?: Prisma.JournalLineUpsertWithWhereUniqueWithoutJournalInput | Prisma.JournalLineUpsertWithWhereUniqueWithoutJournalInput[]
  createMany?: Prisma.JournalLineCreateManyJournalInputEnvelope
  set?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  disconnect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  delete?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  connect?: Prisma.JournalLineWhereUniqueInput | Prisma.JournalLineWhereUniqueInput[]
  update?: Prisma.JournalLineUpdateWithWhereUniqueWithoutJournalInput | Prisma.JournalLineUpdateWithWhereUniqueWithoutJournalInput[]
  updateMany?: Prisma.JournalLineUpdateManyWithWhereWithoutJournalInput | Prisma.JournalLineUpdateManyWithWhereWithoutJournalInput[]
  deleteMany?: Prisma.JournalLineScalarWhereInput | Prisma.JournalLineScalarWhereInput[]
}

export type JournalLineCreateWithoutAccountInput = {
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
  journal: Prisma.JournalEntryCreateNestedOneWithoutLinesInput
}

export type JournalLineUncheckedCreateWithoutAccountInput = {
  id?: number
  journalId: number
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
}

export type JournalLineCreateOrConnectWithoutAccountInput = {
  where: Prisma.JournalLineWhereUniqueInput
  create: Prisma.XOR<Prisma.JournalLineCreateWithoutAccountInput, Prisma.JournalLineUncheckedCreateWithoutAccountInput>
}

export type JournalLineCreateManyAccountInputEnvelope = {
  data: Prisma.JournalLineCreateManyAccountInput | Prisma.JournalLineCreateManyAccountInput[]
  skipDuplicates?: boolean
}

export type JournalLineUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.JournalLineWhereUniqueInput
  update: Prisma.XOR<Prisma.JournalLineUpdateWithoutAccountInput, Prisma.JournalLineUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.JournalLineCreateWithoutAccountInput, Prisma.JournalLineUncheckedCreateWithoutAccountInput>
}

export type JournalLineUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.JournalLineWhereUniqueInput
  data: Prisma.XOR<Prisma.JournalLineUpdateWithoutAccountInput, Prisma.JournalLineUncheckedUpdateWithoutAccountInput>
}

export type JournalLineUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.JournalLineScalarWhereInput
  data: Prisma.XOR<Prisma.JournalLineUpdateManyMutationInput, Prisma.JournalLineUncheckedUpdateManyWithoutAccountInput>
}

export type JournalLineScalarWhereInput = {
  AND?: Prisma.JournalLineScalarWhereInput | Prisma.JournalLineScalarWhereInput[]
  OR?: Prisma.JournalLineScalarWhereInput[]
  NOT?: Prisma.JournalLineScalarWhereInput | Prisma.JournalLineScalarWhereInput[]
  id?: Prisma.IntFilter<"JournalLine"> | number
  journalId?: Prisma.IntFilter<"JournalLine"> | number
  accountId?: Prisma.IntFilter<"JournalLine"> | number
  description?: Prisma.StringNullableFilter<"JournalLine"> | string | null
  debit?: Prisma.DecimalFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFilter<"JournalLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFilter<"JournalLine"> | number
}

export type JournalLineCreateWithoutJournalInput = {
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
  account: Prisma.AccountCreateNestedOneWithoutJournalLinesInput
}

export type JournalLineUncheckedCreateWithoutJournalInput = {
  id?: number
  accountId: number
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
}

export type JournalLineCreateOrConnectWithoutJournalInput = {
  where: Prisma.JournalLineWhereUniqueInput
  create: Prisma.XOR<Prisma.JournalLineCreateWithoutJournalInput, Prisma.JournalLineUncheckedCreateWithoutJournalInput>
}

export type JournalLineCreateManyJournalInputEnvelope = {
  data: Prisma.JournalLineCreateManyJournalInput | Prisma.JournalLineCreateManyJournalInput[]
  skipDuplicates?: boolean
}

export type JournalLineUpsertWithWhereUniqueWithoutJournalInput = {
  where: Prisma.JournalLineWhereUniqueInput
  update: Prisma.XOR<Prisma.JournalLineUpdateWithoutJournalInput, Prisma.JournalLineUncheckedUpdateWithoutJournalInput>
  create: Prisma.XOR<Prisma.JournalLineCreateWithoutJournalInput, Prisma.JournalLineUncheckedCreateWithoutJournalInput>
}

export type JournalLineUpdateWithWhereUniqueWithoutJournalInput = {
  where: Prisma.JournalLineWhereUniqueInput
  data: Prisma.XOR<Prisma.JournalLineUpdateWithoutJournalInput, Prisma.JournalLineUncheckedUpdateWithoutJournalInput>
}

export type JournalLineUpdateManyWithWhereWithoutJournalInput = {
  where: Prisma.JournalLineScalarWhereInput
  data: Prisma.XOR<Prisma.JournalLineUpdateManyMutationInput, Prisma.JournalLineUncheckedUpdateManyWithoutJournalInput>
}

export type JournalLineCreateManyAccountInput = {
  id?: number
  journalId: number
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
}

export type JournalLineUpdateWithoutAccountInput = {
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  journal?: Prisma.JournalEntryUpdateOneRequiredWithoutLinesNestedInput
}

export type JournalLineUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journalId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type JournalLineUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journalId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type JournalLineCreateManyJournalInput = {
  id?: number
  accountId: number
  description?: string | null
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: number
}

export type JournalLineUpdateWithoutJournalInput = {
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  account?: Prisma.AccountUpdateOneRequiredWithoutJournalLinesNestedInput
}

export type JournalLineUncheckedUpdateWithoutJournalInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type JournalLineUncheckedUpdateManyWithoutJournalInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}



export type JournalLineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  journalId?: boolean
  accountId?: boolean
  description?: boolean
  debit?: boolean
  credit?: boolean
  sortOrder?: boolean
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["journalLine"]>

export type JournalLineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  journalId?: boolean
  accountId?: boolean
  description?: boolean
  debit?: boolean
  credit?: boolean
  sortOrder?: boolean
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["journalLine"]>

export type JournalLineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  journalId?: boolean
  accountId?: boolean
  description?: boolean
  debit?: boolean
  credit?: boolean
  sortOrder?: boolean
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["journalLine"]>

export type JournalLineSelectScalar = {
  id?: boolean
  journalId?: boolean
  accountId?: boolean
  description?: boolean
  debit?: boolean
  credit?: boolean
  sortOrder?: boolean
}

export type JournalLineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "journalId" | "accountId" | "description" | "debit" | "credit" | "sortOrder", ExtArgs["result"]["journalLine"]>
export type JournalLineInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}
export type JournalLineIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}
export type JournalLineIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}

export type $JournalLinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JournalLine"
  objects: {
    journal: Prisma.$JournalEntryPayload<ExtArgs>
    account: Prisma.$AccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    journalId: number
    accountId: number
    description: string | null
    debit: runtime.Decimal
    credit: runtime.Decimal
    sortOrder: number
  }, ExtArgs["result"]["journalLine"]>
  composites: {}
}

export type JournalLineGetPayload<S extends boolean | null | undefined | JournalLineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JournalLinePayload, S>

export type JournalLineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JournalLineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JournalLineCountAggregateInputType | true
  }

export interface JournalLineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JournalLine'], meta: { name: 'JournalLine' } }
  /**
   * Find zero or one JournalLine that matches the filter.
   * @param {JournalLineFindUniqueArgs} args - Arguments to find a JournalLine
   * @example
   * // Get one JournalLine
   * const journalLine = await prisma.journalLine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JournalLineFindUniqueArgs>(args: Prisma.SelectSubset<T, JournalLineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JournalLine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JournalLineFindUniqueOrThrowArgs} args - Arguments to find a JournalLine
   * @example
   * // Get one JournalLine
   * const journalLine = await prisma.journalLine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JournalLineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JournalLineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JournalLine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineFindFirstArgs} args - Arguments to find a JournalLine
   * @example
   * // Get one JournalLine
   * const journalLine = await prisma.journalLine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JournalLineFindFirstArgs>(args?: Prisma.SelectSubset<T, JournalLineFindFirstArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JournalLine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineFindFirstOrThrowArgs} args - Arguments to find a JournalLine
   * @example
   * // Get one JournalLine
   * const journalLine = await prisma.journalLine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JournalLineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JournalLineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JournalLines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JournalLines
   * const journalLines = await prisma.journalLine.findMany()
   * 
   * // Get first 10 JournalLines
   * const journalLines = await prisma.journalLine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const journalLineWithIdOnly = await prisma.journalLine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JournalLineFindManyArgs>(args?: Prisma.SelectSubset<T, JournalLineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JournalLine.
   * @param {JournalLineCreateArgs} args - Arguments to create a JournalLine.
   * @example
   * // Create one JournalLine
   * const JournalLine = await prisma.journalLine.create({
   *   data: {
   *     // ... data to create a JournalLine
   *   }
   * })
   * 
   */
  create<T extends JournalLineCreateArgs>(args: Prisma.SelectSubset<T, JournalLineCreateArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JournalLines.
   * @param {JournalLineCreateManyArgs} args - Arguments to create many JournalLines.
   * @example
   * // Create many JournalLines
   * const journalLine = await prisma.journalLine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JournalLineCreateManyArgs>(args?: Prisma.SelectSubset<T, JournalLineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JournalLines and returns the data saved in the database.
   * @param {JournalLineCreateManyAndReturnArgs} args - Arguments to create many JournalLines.
   * @example
   * // Create many JournalLines
   * const journalLine = await prisma.journalLine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JournalLines and only return the `id`
   * const journalLineWithIdOnly = await prisma.journalLine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JournalLineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JournalLineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JournalLine.
   * @param {JournalLineDeleteArgs} args - Arguments to delete one JournalLine.
   * @example
   * // Delete one JournalLine
   * const JournalLine = await prisma.journalLine.delete({
   *   where: {
   *     // ... filter to delete one JournalLine
   *   }
   * })
   * 
   */
  delete<T extends JournalLineDeleteArgs>(args: Prisma.SelectSubset<T, JournalLineDeleteArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JournalLine.
   * @param {JournalLineUpdateArgs} args - Arguments to update one JournalLine.
   * @example
   * // Update one JournalLine
   * const journalLine = await prisma.journalLine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JournalLineUpdateArgs>(args: Prisma.SelectSubset<T, JournalLineUpdateArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JournalLines.
   * @param {JournalLineDeleteManyArgs} args - Arguments to filter JournalLines to delete.
   * @example
   * // Delete a few JournalLines
   * const { count } = await prisma.journalLine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JournalLineDeleteManyArgs>(args?: Prisma.SelectSubset<T, JournalLineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JournalLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JournalLines
   * const journalLine = await prisma.journalLine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JournalLineUpdateManyArgs>(args: Prisma.SelectSubset<T, JournalLineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JournalLines and returns the data updated in the database.
   * @param {JournalLineUpdateManyAndReturnArgs} args - Arguments to update many JournalLines.
   * @example
   * // Update many JournalLines
   * const journalLine = await prisma.journalLine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JournalLines and only return the `id`
   * const journalLineWithIdOnly = await prisma.journalLine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JournalLineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JournalLineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JournalLine.
   * @param {JournalLineUpsertArgs} args - Arguments to update or create a JournalLine.
   * @example
   * // Update or create a JournalLine
   * const journalLine = await prisma.journalLine.upsert({
   *   create: {
   *     // ... data to create a JournalLine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JournalLine we want to update
   *   }
   * })
   */
  upsert<T extends JournalLineUpsertArgs>(args: Prisma.SelectSubset<T, JournalLineUpsertArgs<ExtArgs>>): Prisma.Prisma__JournalLineClient<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JournalLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineCountArgs} args - Arguments to filter JournalLines to count.
   * @example
   * // Count the number of JournalLines
   * const count = await prisma.journalLine.count({
   *   where: {
   *     // ... the filter for the JournalLines we want to count
   *   }
   * })
  **/
  count<T extends JournalLineCountArgs>(
    args?: Prisma.Subset<T, JournalLineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JournalLineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JournalLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JournalLineAggregateArgs>(args: Prisma.Subset<T, JournalLineAggregateArgs>): Prisma.PrismaPromise<GetJournalLineAggregateType<T>>

  /**
   * Group by JournalLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalLineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JournalLineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JournalLineGroupByArgs['orderBy'] }
      : { orderBy?: JournalLineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JournalLineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJournalLineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JournalLine model
 */
readonly fields: JournalLineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JournalLine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JournalLineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  journal<T extends Prisma.JournalEntryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JournalEntryDefaultArgs<ExtArgs>>): Prisma.Prisma__JournalEntryClient<runtime.Types.Result.GetResult<Prisma.$JournalEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  account<T extends Prisma.AccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JournalLine model
 */
export interface JournalLineFieldRefs {
  readonly id: Prisma.FieldRef<"JournalLine", 'Int'>
  readonly journalId: Prisma.FieldRef<"JournalLine", 'Int'>
  readonly accountId: Prisma.FieldRef<"JournalLine", 'Int'>
  readonly description: Prisma.FieldRef<"JournalLine", 'String'>
  readonly debit: Prisma.FieldRef<"JournalLine", 'Decimal'>
  readonly credit: Prisma.FieldRef<"JournalLine", 'Decimal'>
  readonly sortOrder: Prisma.FieldRef<"JournalLine", 'Int'>
}
    

// Custom InputTypes
/**
 * JournalLine findUnique
 */
export type JournalLineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * Filter, which JournalLine to fetch.
   */
  where: Prisma.JournalLineWhereUniqueInput
}

/**
 * JournalLine findUniqueOrThrow
 */
export type JournalLineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * Filter, which JournalLine to fetch.
   */
  where: Prisma.JournalLineWhereUniqueInput
}

/**
 * JournalLine findFirst
 */
export type JournalLineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * Filter, which JournalLine to fetch.
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalLines to fetch.
   */
  orderBy?: Prisma.JournalLineOrderByWithRelationInput | Prisma.JournalLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JournalLines.
   */
  cursor?: Prisma.JournalLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JournalLines.
   */
  distinct?: Prisma.JournalLineScalarFieldEnum | Prisma.JournalLineScalarFieldEnum[]
}

/**
 * JournalLine findFirstOrThrow
 */
export type JournalLineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * Filter, which JournalLine to fetch.
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalLines to fetch.
   */
  orderBy?: Prisma.JournalLineOrderByWithRelationInput | Prisma.JournalLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JournalLines.
   */
  cursor?: Prisma.JournalLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JournalLines.
   */
  distinct?: Prisma.JournalLineScalarFieldEnum | Prisma.JournalLineScalarFieldEnum[]
}

/**
 * JournalLine findMany
 */
export type JournalLineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * Filter, which JournalLines to fetch.
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalLines to fetch.
   */
  orderBy?: Prisma.JournalLineOrderByWithRelationInput | Prisma.JournalLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JournalLines.
   */
  cursor?: Prisma.JournalLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JournalLines.
   */
  distinct?: Prisma.JournalLineScalarFieldEnum | Prisma.JournalLineScalarFieldEnum[]
}

/**
 * JournalLine create
 */
export type JournalLineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * The data needed to create a JournalLine.
   */
  data: Prisma.XOR<Prisma.JournalLineCreateInput, Prisma.JournalLineUncheckedCreateInput>
}

/**
 * JournalLine createMany
 */
export type JournalLineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JournalLines.
   */
  data: Prisma.JournalLineCreateManyInput | Prisma.JournalLineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JournalLine createManyAndReturn
 */
export type JournalLineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * The data used to create many JournalLines.
   */
  data: Prisma.JournalLineCreateManyInput | Prisma.JournalLineCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * JournalLine update
 */
export type JournalLineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * The data needed to update a JournalLine.
   */
  data: Prisma.XOR<Prisma.JournalLineUpdateInput, Prisma.JournalLineUncheckedUpdateInput>
  /**
   * Choose, which JournalLine to update.
   */
  where: Prisma.JournalLineWhereUniqueInput
}

/**
 * JournalLine updateMany
 */
export type JournalLineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JournalLines.
   */
  data: Prisma.XOR<Prisma.JournalLineUpdateManyMutationInput, Prisma.JournalLineUncheckedUpdateManyInput>
  /**
   * Filter which JournalLines to update
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * Limit how many JournalLines to update.
   */
  limit?: number
}

/**
 * JournalLine updateManyAndReturn
 */
export type JournalLineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * The data used to update JournalLines.
   */
  data: Prisma.XOR<Prisma.JournalLineUpdateManyMutationInput, Prisma.JournalLineUncheckedUpdateManyInput>
  /**
   * Filter which JournalLines to update
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * Limit how many JournalLines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * JournalLine upsert
 */
export type JournalLineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * The filter to search for the JournalLine to update in case it exists.
   */
  where: Prisma.JournalLineWhereUniqueInput
  /**
   * In case the JournalLine found by the `where` argument doesn't exist, create a new JournalLine with this data.
   */
  create: Prisma.XOR<Prisma.JournalLineCreateInput, Prisma.JournalLineUncheckedCreateInput>
  /**
   * In case the JournalLine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JournalLineUpdateInput, Prisma.JournalLineUncheckedUpdateInput>
}

/**
 * JournalLine delete
 */
export type JournalLineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  /**
   * Filter which JournalLine to delete.
   */
  where: Prisma.JournalLineWhereUniqueInput
}

/**
 * JournalLine deleteMany
 */
export type JournalLineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JournalLines to delete
   */
  where?: Prisma.JournalLineWhereInput
  /**
   * Limit how many JournalLines to delete.
   */
  limit?: number
}

/**
 * JournalLine without action
 */
export type JournalLineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
}
